"""Picture Studio · smart levels: collocations and actions on the same picture.

A1-A2 learners click the things (window, door, table). From B1 the picture
also answers with what people DO there - "feed the ducks", "check in your
bags", "cast a spell". Each phrase is pinned to a thing that is already in the
scene (the anchor), so no drawing changes; Scene.save() merges them in as
parts with pos "phrase". The studio's level window (scene-studio.js) shows
A1 → A1, A2 → A1-A2, B1 → A2-B1 + B1 phrases, B2 → B1-B2 + all phrases.

    (id, phrase, level, anchor part id, definition, example)
"""

ACTS = {
    "park": [
        ("kite", "fly a kite", "B1", "kite", "To make a kite rise and stay up in the wind.", "The kids are flying a kite on the hill."),
        ("ducks", "feed the ducks", "B1", "ducks", "To give food to the ducks on the water.", "We fed the ducks with some seeds."),
        ("picnic", "have a picnic", "B1", "blanket", "To eat a meal outdoors, usually sitting on the grass.", "Let's have a picnic by the pond."),
        ("jog", "go for a jog", "B1", "jogger", "To run slowly for exercise.", "He goes for a jog before work."),
        ("walk", "take the dog for a walk", "B2", "dog", "To walk with your dog so that it gets some exercise.", "She takes the dog for a walk every evening."),
        ("sun", "soak up the sun", "B2", "sun", "To enjoy sitting or lying in warm sunshine.", "They lay on the grass, soaking up the sun."),
        ("treat", "treat yourself to an ice cream", "B2", "icecream", "To buy something nice for yourself as a small reward.", "After the run she treated herself to an ice cream."),
    ],
    "house": [
        ("washup", "do the washing-up", "B1", "sink", "To wash the plates, cups and pans after a meal.", "It's your turn to do the washing-up."),
        ("bed", "make the bed", "B1", "bed", "To tidy the sheets and duvet after you get up.", "I always make my bed in the morning."),
        ("bell", "ring the doorbell", "B1", "doorbell", "To press the button that makes a sound inside the house.", "Someone is ringing the doorbell."),
        ("mow", "mow the lawn", "B1", "lawnmower", "To cut the grass with a lawnmower.", "Dad mows the lawn every Saturday."),
        ("feet", "put your feet up", "B2", "sofa", "To sit down and relax, especially after hard work.", "After a long day she put her feet up on the sofa."),
        ("attic", "clear out the attic", "B2", "boxes", "To remove the things you no longer need from the attic.", "We finally cleared out the attic last weekend."),
        ("bath", "run a bath", "B2", "bath", "To fill a bath with water so that someone can use it.", "I'll run you a nice hot bath."),
    ],
    "kitchen": [
        ("kettle", "boil the kettle", "B1", "kettle", "To heat water in the kettle until it boils.", "I'll boil the kettle and make some tea."),
        ("lay", "lay the table", "B1", "table", "To put plates, knives and forks on the table before a meal.", "Can you lay the table for four?"),
        ("load", "load the dishwasher", "B1", "dishwasher", "To put dirty dishes into the dishwasher.", "Please load the dishwasher after dinner."),
        ("recipe", "follow a recipe", "B1", "cookbooks", "To cook something by doing what the instructions say.", "I followed the recipe exactly, but the cake sank."),
        ("chop", "chop up the vegetables", "B2", "choppingboard", "To cut vegetables into small pieces.", "Chop up the onions while the pan heats up."),
        ("stir", "stir the soup", "B2", "saucepan", "To move a spoon round and round in a liquid.", "Keep stirring the soup so it doesn't burn."),
        ("whisk", "whisk the eggs", "B2", "whisk", "To mix eggs quickly until they are light.", "Whisk the eggs with a little milk."),
    ],
    "airport": [
        ("checkin", "check in your bags", "B1", "suitcase", "To give your suitcase to the airline before a flight.", "We checked in our bags two hours early."),
        ("security", "go through security", "B1", "detector", "To pass the checks where they look at you and your bags.", "Take off your belt before you go through security."),
        ("board", "board the plane", "B1", "jetbridge", "To get on the plane.", "Passengers can now board the plane."),
        ("collect", "collect your luggage", "B1", "carousel", "To pick up your bags after a flight.", "We collected our luggage from carousel 4."),
        ("delay", "the flight is delayed", "B2", "board", "The plane will leave later than planned.", "Our flight is delayed by two hours because of fog."),
        ("passport", "have your passport checked", "B2", "officer", "To let an officer look at your passport.", "You have to have your passport checked before the gate."),
        ("connect", "catch a connecting flight", "B2", "gatesign", "To take a second flight to continue your journey.", "We only had forty minutes to catch our connecting flight."),
    ],
    "car": [
        ("fill", "fill up the tank", "B1", "pump", "To put petrol in the car until it is full.", "We need to fill up the tank before the motorway."),
        ("belt", "fasten your seat belt", "B1", "seatbelt", "To close the safety belt across your body.", "Please fasten your seat belt."),
        ("lights", "turn on the headlights", "B1", "headlights", "To switch on the big lights at the front of the car.", "It's getting dark - turn on the headlights."),
        ("red", "stop at a red light", "B1", "trafficlights", "To stop the car when the traffic light is red.", "Always stop at a red light, even at night."),
        ("tyres", "check the tyre pressure", "B2", "tyre", "To measure how much air is in the tyres.", "Check the tyre pressure before a long trip."),
        ("gear", "change gear", "B2", "gearstick", "To move the gear stick to go faster or slower.", "You need to change gear when you go up the hill."),
        ("pull", "pull over", "B2", "kerb", "To move the car to the side of the road and stop.", "The police told us to pull over."),
    ],
    "hospital": [
        ("call", "call an ambulance", "B1", "ambulance", "To phone for an ambulance in an emergency.", "Call an ambulance - he's hurt!"),
        ("eyes", "have an eye test", "B1", "eyechart", "To have your eyesight checked.", "I had an eye test and now I need glasses."),
        ("appt", "book an appointment", "B1", "receptionist", "To arrange a time to see a doctor.", "I'd like to book an appointment with Dr Lee."),
        ("pres", "pick up a prescription", "B1", "prescription", "To collect the medicine a doctor has ordered for you.", "I picked up my prescription at the pharmacy."),
        ("op", "have an operation", "B2", "operatingtable", "When doctors cut your body to repair something inside.", "She had an operation on her knee."),
        ("arm", "break your arm", "B2", "sling", "To crack a bone in your arm.", "He broke his arm playing football."),
        ("drip", "be on a drip", "B2", "drip", "To get liquid medicine through a tube into your arm.", "The patient was on a drip for two days."),
    ],
    "school": [
        ("hand", "put your hand up", "B1", "pupil", "To raise your hand when you want to speak in class.", "Put your hand up if you know the answer."),
        ("homework", "hand in your homework", "B1", "schoolbag", "To give your finished homework to the teacher.", "Hand in your homework by Friday."),
        ("borrow", "borrow a book", "B1", "books", "To take a book from the library and bring it back later.", "You can borrow three books at a time."),
        ("bus", "catch the bus", "B1", "bus", "To get on the bus in time.", "I catch the bus at 7.45 every morning."),
        ("notes", "take notes", "B2", "notebook", "To write down the important points.", "Take notes while you listen."),
        ("whistle", "blow the whistle", "B2", "whistle", "To make a loud sound with a whistle, usually to stop a game.", "The PE teacher blew the whistle and everyone stopped."),
        ("queue", "queue up for lunch", "B2", "tray", "To wait in a line to get your lunch.", "We queued up for lunch for ten minutes."),
    ],
    "supermarket": [
        ("push", "push a trolley", "B1", "trolley", "To move a shopping trolley along the aisles.", "The little boy wanted to push the trolley."),
        ("card", "pay by card", "B1", "card", "To pay with a bank card instead of cash.", "Can I pay by card?"),
        ("weigh", "weigh the fruit", "B1", "scales", "To find out how heavy the fruit is.", "Weigh the apples before you go to the checkout."),
        ("receipt", "keep the receipt", "B1", "receipt", "To keep the paper that shows what you paid.", "Keep the receipt in case you need to return it."),
        ("bargain", "get a bargain", "B2", "offer", "To buy something for less than its usual price.", "Two for one - that's a real bargain!"),
        ("pack", "pack your shopping", "B2", "bag", "To put the things you bought into bags.", "She packed her shopping while the cashier scanned it."),
        ("runout", "run out of milk", "B2", "milk", "To use all of something so that none is left.", "We've run out of milk again."),
    ],
    "street": [
        ("cash", "take out some cash", "B1", "cashmachine", "To get money from a cash machine.", "I need to take out some cash first."),
        ("post", "post a letter", "B1", "postbox", "To put a letter in a postbox.", "Can you post this letter for me?"),
        ("cross", "cross the road", "B1", "zebra", "To go from one side of the road to the other.", "Always cross the road at the zebra crossing."),
        ("wait", "wait for the bus", "B1", "shelter", "To stay at the bus stop until the bus comes.", "We waited for the bus for twenty minutes."),
        ("window", "go window shopping", "B2", "shopwindow", "To look at things in shop windows without buying anything.", "We went window shopping on Saturday afternoon."),
        ("cycle", "cycle to work", "B2", "cyclist", "To go to work by bike.", "He cycles to work to keep fit."),
        ("grab", "grab a coffee", "B2", "table", "To get a quick coffee.", "Let's grab a coffee before the meeting."),
    ],
    "station": [
        ("ticket", "buy a ticket", "B1", "machine", "To pay for a ticket at the machine or the ticket office.", "You can buy a ticket from the machine."),
        ("timetable", "check the timetable", "B1", "timetable", "To look at the times the trains leave.", "Check the timetable before you leave home."),
        ("miss", "miss the train", "B1", "train", "To arrive too late to get on the train.", "Hurry up or we'll miss the train!"),
        ("line", "stand behind the yellow line", "B1", "yellowline", "To wait at a safe distance from the edge of the platform.", "Please stand behind the yellow line."),
        ("late", "the train is running late", "B2", "board", "The train will arrive later than planned.", "The 8.15 is running ten minutes late."),
        ("flag", "wave the flag", "B2", "flag", "To move a flag to give a signal.", "The guard waved the flag and the train left."),
        ("announce", "make an announcement", "B2", "loudspeaker", "To tell everyone something important through a loudspeaker.", "They made an announcement about the delay."),
    ],
    "restaurant": [
        ("book", "book a table", "B1", "table", "To ask the restaurant to keep a table for you.", "I've booked a table for eight o'clock."),
        ("order", "take an order", "B1", "notepad", "To write down what the customers want to eat.", "The waitress is taking their order."),
        ("tip", "leave a tip", "B1", "tipjar", "To give extra money to say thank you for good service.", "The food was great, so we left a big tip."),
        ("menu", "look at the menu", "B1", "menu", "To read the list of food and drinks.", "Could we look at the menu, please?"),
        ("special", "try today's special", "B2", "specials", "To order the dish the restaurant offers only today.", "I think I'll try today's special."),
        ("candle", "light a candle", "B2", "candle", "To make a candle start burning.", "The waiter lit a candle on our table."),
        ("serve", "serve up a dish", "B2", "dishes", "To put food on plates and bring it to people.", "The chef served up three dishes at once."),
    ],
    "gothicdorm": [
        ("mystery", "solve a mystery", "B1", "magnifier", "To find out the truth about something strange.", "She won't sleep until she solves the mystery."),
        ("light", "light the candles", "B1", "candelabra", "To make the candles start burning.", "She lit the candles and started to type."),
        ("cello", "play the cello", "B1", "cello", "To make music on a cello.", "She plays the cello late at night."),
        ("type", "type a story", "B1", "typewriter", "To write a story using the keys of a machine.", "She types a new chapter of her story every night."),
        ("secret", "keep a secret", "B2", "trunk", "To not tell anyone something private.", "Can you keep a secret? It's in the trunk."),
        ("sneak", "sneak out at night", "B2", "passage", "To leave quietly so that nobody sees you.", "They sneaked out through the hidden passage at midnight."),
        ("share", "share a room with someone", "B2", "roommate", "To live in the same room as another person.", "She has to share a room with someone very cheerful."),
        ("brighten", "brighten up a room", "B2", "lights", "To make a room look more cheerful.", "Fairy lights really brighten up a room."),
    ],
    "potions": [
        ("brew", "brew a potion", "B1", "cauldron", "To make a magic drink by cooking it.", "The students are brewing a potion for luck."),
        ("stir", "stir the cauldron", "B1", "spoon", "To move a spoon round and round in the pot.", "Stir the cauldron seven times, then stop."),
        ("spell", "cast a spell", "B1", "wand", "To use magic words to make something happen.", "She cast a spell and the candles lit up."),
        ("recipe", "follow the recipe", "B1", "recipe", "To do each step exactly as the instructions say.", "If you don't follow the recipe, it will explode."),
        ("drops", "add three drops", "B2", "bottles", "To put three very small amounts of a liquid into something.", "Add three drops of the blue potion - no more!"),
        ("measure", "measure the ingredients", "B2", "scales", "To find out exactly how much of each thing you need.", "Measure the ingredients carefully on the scales."),
        ("crush", "crush the herbs", "B2", "mortar", "To press leaves until they break into tiny pieces.", "Crush the herbs into a fine powder."),
    ],
    "starship": [
        ("steer", "steer the ship", "B1", "stick", "To control the direction the ship goes in.", "The pilot steers the ship round the comet."),
        ("alarm", "sound the alarm", "B1", "light", "To make a warning signal start.", "The robot sounded the alarm when it saw the asteroid."),
        ("repair", "repair the engine", "B1", "panel", "To fix the engine when it is broken.", "The engineer needs an hour to repair the engine."),
        ("suit", "put on a spacesuit", "B1", "spacesuit", "To dress in the special clothes for space.", "Put on a spacesuit before you go outside."),
        ("course", "set a course for a planet", "B2", "map", "To choose the direction to travel to a planet.", "Set a course for the ringed planet."),
        ("shields", "raise the shields", "B2", "shields", "To switch on the ship's protection.", "Raise the shields - something is coming!"),
        ("orders", "give orders", "B2", "captain", "To tell people what they must do.", "The captain gives orders calmly, even in danger."),
        ("scan", "scan the planet", "B2", "planet", "To examine a planet with special instruments.", "We scanned the planet for signs of life."),
    ],
    "herolab": [
        ("invent", "invent a gadget", "B1", "drone", "To create a new clever machine.", "She invented a gadget that can see through walls."),
        ("upgrade", "upgrade the suit", "B1", "suit", "To make the suit better and more powerful.", "She's upgrading the suit so it can fly higher."),
        ("test", "run a test", "B1", "tubes", "To do an experiment to check something.", "Let's run a test on the green liquid."),
        ("charge", "charge the battery", "B1", "battery", "To fill a battery with electricity.", "The robotic arm is charging the battery."),
        ("rules", "follow the safety rules", "B1", "sign", "To do what the rules say so that nobody gets hurt.", "Everyone must follow the safety rules in the lab."),
        ("care", "handle with care", "B2", "crystal", "To touch or move something very carefully.", "The crystal is unstable - handle with care."),
        ("contain", "contain the threat", "B2", "cell", "To stop something dangerous from spreading.", "The team managed to contain the threat."),
        ("data", "analyse the data", "B2", "screens", "To study information carefully to understand it.", "The AI assistant is analysing the data from the city."),
    ],
    "treasure": [
        ("explore", "explore a cave", "B1", "entrance", "To travel into a cave to find out what is inside.", "They spent the whole day exploring the cave."),
        ("climb", "climb down a rope", "B1", "rope", "To go down holding onto a rope.", "She climbed down the rope into the dark."),
        ("readmap", "read a map", "B1", "map", "To understand where you are and where to go from a map.", "Can you read a map without a phone?"),
        ("avoid", "avoid the trap", "B1", "trap", "To keep away from the trap so it doesn't catch you.", "Walk round the edge to avoid the trap."),
        ("find", "find the treasure", "B1", "chest", "To discover where the treasure is.", "After three days they finally found the treasure."),
        ("decipher", "decipher the symbols", "B2", "carvings", "To work out what old or secret writing means.", "Only she could decipher the symbols on the wall."),
        ("escape", "escape just in time", "B2", "entrance", "To get away only a moment before something bad happens.", "The roof fell in, but they escaped just in time."),
        ("light", "light the way", "B2", "torch", "To carry a light so others can see where to go.", "Take the torch and light the way."),
    ],
    "frontier": [
        ("ride", "ride a horse", "B1", "horse", "To sit on a horse and control it as it moves.", "Can you ride a horse?"),
        ("tie", "tie up the horse", "B1", "post", "To fasten the horse to something with a rope.", "He tied up his horse outside the saloon."),
        ("supplies", "buy supplies", "B1", "store", "To buy the food and things you need for a trip.", "They bought supplies at the general store."),
        ("law", "keep the peace", "B2", "sheriff", "To stop fighting and trouble in a place.", "The sheriff's job is to keep the peace."),
        ("jailed", "be locked up", "B1", "jail", "To be put in a room you cannot leave.", "The robber was locked up for the night."),
        ("reward", "offer a reward", "B2", "poster", "To promise money to someone who helps.", "They're offering a reward of 500 dollars."),
        ("heat", "shelter from the heat", "B2", "porch", "To stay in the shade so the sun doesn't burn you.", "They sheltered from the heat on the porch."),
        ("coach", "catch the stagecoach", "B1", "coach", "To get on the stagecoach before it leaves.", "She caught the stagecoach to the next town."),
    ],
    "office": [
        ("brainstorm", "brainstorm ideas", "B1", "whiteboard", "To think of lots of ideas together quickly.", "Let's brainstorm ideas for the new app."),
        ("call", "join a video call", "B1", "screen", "To start taking part in a call on a screen.", "Can you join the video call at ten?"),
        ("break", "take a coffee break", "B1", "coffeemachine", "To stop working for a short time and have a coffee.", "We take a coffee break at eleven."),
        ("print", "print a document", "B1", "printer", "To put a document on paper using a printer.", "I need to print a document for the meeting."),
        ("deadline", "meet a deadline", "B2", "deadline", "To finish work by the time it is due.", "We worked late to meet the deadline."),
        ("remote", "work remotely", "B2", "remote", "To work from home or another place, not the office.", "She works remotely three days a week."),
        ("book", "book a meeting room", "B2", "table", "To reserve a meeting room for a certain time.", "I've booked a meeting room for two o'clock."),
        ("focus", "focus on your work", "B2", "headphones", "To give all your attention to your work.", "Headphones help me focus on my work."),
    ],
    "gym": [
        ("run", "go for a run", "B1", "treadmill", "To run for exercise.", "She goes for a run on the treadmill every morning."),
        ("lift", "lift weights", "B1", "dumbbell", "To raise heavy weights to make your muscles stronger.", "He lifts weights three times a week."),
        ("stretch", "stretch your muscles", "B1", "mat", "To make your muscles longer so they don't get hurt.", "Always stretch your muscles after a workout."),
        ("warmup", "warm up", "B1", "bike", "To do gentle exercise before harder exercise.", "Warm up on the bike for five minutes."),
        ("hydrated", "stay hydrated", "B2", "bottle", "To drink enough water so your body doesn't dry out.", "Stay hydrated - drink water between sets."),
        ("reps", "do ten reps", "B2", "lifter", "To repeat an exercise ten times.", "Do ten reps, rest, then do ten more."),
        ("fit", "keep fit", "B2", "trainer", "To stay healthy and strong by exercising.", "Her trainer helps her keep fit."),
        ("sweat", "work up a sweat", "B2", "runner", "To exercise so hard that you start sweating.", "Ten minutes on the treadmill and you'll work up a sweat."),
    ],
}

# B2 writing and speaking tasks (the studio falls back to B1 where a scene has none).
PROMPTS_B2 = {
    "park": ["Should dogs be allowed off the lead in city parks? Argue both sides.",
             "Describe a perfect afternoon in the park using at least five phrases from the picture.",
             "Write a proposal to improve a park near you."],
    "house": ["Which household chores should children do? Give reasons.",
              "Describe how you would turn the attic into a room.",
              "Write about the room in your home where you can really put your feet up."],
    "kitchen": ["Write a recipe for a dish from your country, step by step.",
                "Is cooking at home better than eating out? Discuss.",
                "Describe what goes wrong in a kitchen disaster."],
    "airport": ["Tell the story of a journey where everything went wrong.",
                "Should short flights be banned to protect the climate?",
                "Write a complaint to an airline about a delayed flight."],
    "car": ["Should cities ban cars from the centre? Give your opinion.",
            "Describe what to check before a long car journey.",
            "Tell the story of a time you got lost on the road."],
    "hospital": ["Describe an accident and what happened at the hospital afterwards.",
                 "Should healthcare be free for everyone? Discuss.",
                 "Write a thank-you letter to a nurse or doctor."],
    "school": ["What makes a good teacher? Give examples.",
               "Should homework be banned? Argue both sides.",
               "Describe your ideal school day."],
    "supermarket": ["Are supermarkets killing small shops? Discuss.",
                    "Describe how you plan and do a big weekly shop.",
                    "Write tips for saving money on food."],
    "street": ["What would make your high street a better place?",
               "Online shopping or high street shopping - which is better?",
               "Describe a busy street scene as if you were a writer."],
    "station": ["Should train travel be cheaper than flying? Discuss.",
                "Tell the story of a journey that changed your plans.",
                "Write an announcement about a cancelled train and what passengers should do."],
    "restaurant": ["Write a review of a restaurant you love or hate.",
                   "Should tipping be replaced by higher prices? Discuss.",
                   "Describe the busiest night in a restaurant kitchen."],
    "gothicdorm": ["Describe someone who seems gloomy but is secretly kind. Use at least six adjectives of character.",
                   "Write the first page of a mystery that starts in this room.",
                   "Opposites attract: can very different people be best friends? Discuss."],
    "potions": ["Write a detailed recipe for a potion that solves one problem in your life. Use sequencing words and imperatives.",
                "A potion has gone badly wrong in class. Write the teacher's report.",
                "If you could brew one potion for the whole world, what would it do? Discuss."],
    "starship": ["You are the captain. Write a short speech to the crew before a dangerous mission.",
                 "Speculate about the planet: what could live there and how would you find out?",
                 "Is it right to send humans, not robots, into deep space? Argue your view."],
    "herolab": ["Pitch an invention to investors: the problem, the solution and why they should pay for it.",
                "Should inventors be allowed to build anything they want? Discuss the limits of science.",
                "Write a news report about the night the crystal was contained."],
    "treasure": ["Write a gripping adventure story that ends with the explorers escaping just in time.",
                 "Who should own ancient treasure - the finder, the country or a museum? Discuss.",
                 "Describe the cave so that the reader feels the danger. Use vivid verbs and adjectives."],
    "frontier": ["Write the opening of a Western story with a mysterious stranger. Build tension.",
                 "How did people in small frontier towns survive without modern technology? Speculate.",
                 "Is the 'lone hero' of old Westerns a good role model? Discuss."],
    "office": ["Write a proposal to your manager for a four-day working week.",
               "Hybrid, remote or office: which is best for productivity? Support your view.",
               "Describe how a team should run a good brainstorming session."],
    "gym": ["Design a four-week fitness plan for a beginner and explain the reasons for each stage.",
            "Should gyms be free, like libraries, to improve public health? Discuss.",
            "Describe the atmosphere of a busy gym using the senses."],
}
