window.TEACHEDOS_DATA = {
  tools: [
    { id:'r1', name:'Create a Text on Any Topic with Your Vocabulary', desc:'Paste a topic and a word list to generate a CEFR-friendly text. Great for reading work, homework, or a custom lead-in after a vocabulary lesson.', tags:['Reading','Vocabulary'], badge:null, icon:'📄', group:'reading' },
    { id:'r2', name:'Create ABCD Questions', desc:'Локальний модуль створює multiple-choice запитання з тексту прямо на GitHub Pages без API-ключа. Зручно для швидких reading quizzes.', tags:['Reading'], badge:'New', icon:'🔡', group:'reading' },
    { id:'r3', name:'Create Open Questions', desc:'Produces open-ended comprehension questions that encourage critical thinking and discussion around the text.', tags:['Reading'], badge:null, icon:'❓', group:'reading' },
    { id:'r4', name:'Create True/False Statements', desc:'Creates a true/false reading exercise to quickly check if students understood the key facts and details of the text.', tags:['Reading'], badge:'Pro', icon:'✅', group:'reading' },
    { id:'w1', name:'Writing Prompts', desc:'Generates creative or structured writing prompts tailored to a specific topic and CEFR level — useful for class writing, homework, and exam-style warm-ups.', tags:['Writing'], badge:'New', icon:'✍️', group:'writing' },
    { id:'w2', name:'Dialogue Creator', desc:'Creates a short dialogue between two characters on any topic and level. Use for reading, comprehension, or role-play speaking practice.', tags:['Writing','Speaking'], badge:'New', icon:'💬', group:'writing' },
    { id:'l1', name:'Audio & Video Question Creator', desc:'Upload any audio or video file and auto-generate open questions, multiple-choice questions, or true/false statements based on the content.', tags:['Listening'], badge:'Pro', icon:'🎙️', group:'listening' },
    { id:'l2', name:'Convert Audio & Video to Text', desc:'Transcribes mp3, mp4, or YouTube links into a readable transcript ready for classroom use as a reading or gap-fill activity.', tags:['Listening'], badge:'Pro', icon:'🎬', group:'listening' },
    { id:'s1', name:'Find Discussion Questions', desc:'Creates engaging discussion questions on any topic — use as a warm-up, while-lesson discussion, or speaking fluency practice for any level.', tags:['Speaking'], badge:null, icon:'🗣️', group:'speaking' },
    { id:'s2', name:'Role-Play Scenarios', desc:'Generates role-play cards and scenario prompts for pair or group speaking activities. Set the context and get ready-to-use speaking tasks.', tags:['Speaking'], badge:'New', icon:'🎭', group:'speaking' },
    { id:'s3', name:'Four Opinions Generator', desc:'Генерує 4 різні англомовні позиції за темою, рівнем і довжиною. Добре працює як speaking warm-up або debate starter.', tags:['Speaking'], badge:'New', icon:'🧠', group:'speaking' },
    { id:'v1', name:'Word-Image Matching', desc:'Creates a vocabulary exercise where students match each word to the correct picture. Boosts visual recognition and word retention.', tags:['Vocabulary'], badge:'New', icon:'🖼️', group:'vocabulary' },
    { id:'v2', name:'Word-Definition Matching', desc:'Інтерактивна гра на співставлення слова з визначенням. Перекладено українською та вбудовано прямо в TeachedOS.', tags:['Vocabulary'], badge:'New', icon:'🔍', group:'vocabulary' },
    { id:'v3', name:'Create a List of Sentences with Your Vocabulary', desc:'Generates example sentences using your target vocabulary list. Great before a Fill-in-the-Gap task or as a quick context bank for a new word set.', tags:['Vocabulary'], badge:'Pro', icon:'📋', group:'vocabulary' },
    { id:'v4', name:'Fill in the Gap', desc:'Replaces chosen words in a text with blank gaps and provides the word list separately. Works for vocabulary recall and grammar tense practice.', tags:['Vocabulary','Grammar'], badge:null, icon:'✏️', group:'vocabulary' },
    { id:'g1', name:'Fill in the Gap', desc:'Replaces chosen words in a text with gaps. Add verb forms or tense markers to turn it into a grammar tense or form exercise.', tags:['Grammar','Vocabulary'], badge:null, icon:'✏️', group:'grammar' },
    { id:'g2', name:'Grammar Worksheets', desc:'Generates structured grammar worksheets with clear explanations, examples, and progressive exercises for any grammar point and CEFR level.', tags:['Grammar'], badge:null, icon:'📑', group:'grammar' },
    { id:'g3', name:'Error Correction', desc:'Creates sentences with intentional grammar or vocabulary mistakes for students to identify and fix. Great for proofreading and accuracy tasks.', tags:['Grammar'], badge:'New', icon:'🔧', group:'grammar' },
    { id:'u1', name:'CEFR Level Checker', desc:'Paste any text and instantly determine its CEFR proficiency level (A1–C2) according to the Common European Framework of Reference.', tags:['Utility'], badge:'Pro', icon:'📊', group:'utility' },
    { id:'u2', name:'Lesson Plan Generator', desc:'Input a topic, level, and lesson duration — get a complete, structured lesson plan with objectives, activities, and timing suggestions.', tags:['Utility'], badge:null, icon:'📅', group:'utility' }
  ],
  games: [
    {
      id:'quiz-lab',
      toolId:'r2',
      icon:'🔡',
      accent:'linear-gradient(145deg,#7ca8ff,#356dff)',
      title:'LinguaQuiz AI',
      eyebrow:'§ reading generator',
      subtitle:'ABCD Questions · Local Mode',
      desc:'Локальний модуль для reading practice: вставляєте текст і отримуєте multiple-choice питання прямо у вікні OS без API-ключів і зовнішнього бекенду.',
      skill:'Reading',
      mode:'Offline',
      audience:'A1–C2',
      embedUrl:'games/linguaquiz-ai-uk.html?embed=1',
      rawUrl:'games/linguaquiz-ai-uk.html'
    },
    {
      id:'opinions-lab',
      toolId:'s3',
      icon:'🧠',
      accent:'linear-gradient(145deg,#b687ff,#7f56e3)',
      title:'Four Opinions Generator',
      eyebrow:'§ speaking starter',
      subtitle:'Debate Module · Four Voices',
      desc:'Органічний speaking-модуль для warm-up, pair work та discussion circles. Створює чотири контрастні точки зору англійською в компактному системному режимі.',
      skill:'Speaking',
      mode:'Offline',
      audience:'A1–C1',
      embedUrl:'games/four-opinions-uk.html?embed=1',
      rawUrl:'games/four-opinions-uk.html'
    },
    {
      id:'match-lab',
      toolId:'v2',
      icon:'🔍',
      accent:'linear-gradient(145deg,#ff9a62,#d96b2b)',
      title:'Word-Definition Matching',
      eyebrow:'§ vocabulary module',
      subtitle:'Matching Grid · Embedded',
      desc:'Інтерактивна вправа на співставлення слів і визначень. Перекладена українською і підготовлена як повноцінний модуль TeachedOS, а не окрема сторінка.',
      skill:'Vocabulary',
      mode:'Playable',
      audience:'A2–B2',
      embedUrl:'games/word-definition-match.html?embed=1',
      rawUrl:'games/word-definition-match.html'
    },
    {
      id:'text-builder-lab',
      toolId:'r1',
      icon:'📄',
      accent:'linear-gradient(145deg,#7ca8ff,#4567f4)',
      title:'Text Builder',
      eyebrow:'§ reading generator',
      subtitle:'Topic + Vocabulary · Local Mode',
      desc:'Генерує короткий текст на тему з вашою лексикою і рівнем CEFR. Це наш локальний аналог одного з базових Twee reading modules.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C1',
      embedUrl:'games/twee-module-studio.html?module=text-vocab&embed=1',
      rawUrl:'games/twee-module-studio.html?module=text-vocab'
    },
    {
      id:'open-questions-lab',
      toolId:'r3',
      icon:'❓',
      accent:'linear-gradient(145deg,#84b8ff,#4d91ff)',
      title:'Open Questions',
      eyebrow:'§ reading check',
      subtitle:'Comprehension Questions · Local Mode',
      desc:'Створює відкриті питання до тексту у стилі Twee workflow: швидко, локально і без зовнішніх сервісів.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=open-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=open-questions'
    },
    {
      id:'true-false-lab',
      toolId:'r4',
      icon:'✅',
      accent:'linear-gradient(145deg,#6ed39c,#4fb58b)',
      title:'True / False',
      eyebrow:'§ reading exercise',
      subtitle:'Statement Builder · Local Mode',
      desc:'Генерує true/false вправу на основі тексту. Підходить для короткої comprehension check activity після reading.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=true-false&embed=1',
      rawUrl:'games/twee-module-studio.html?module=true-false'
    },
    {
      id:'discussion-lab',
      toolId:'s1',
      icon:'🗣️',
      accent:'linear-gradient(145deg,#bb8cff,#8f61f1)',
      title:'Discussion Questions',
      eyebrow:'§ speaking warm-up',
      subtitle:'Topic Prompts · Local Mode',
      desc:'Підбирає discussion questions на тему для warm-up, pair work або freer speaking. Органічно закриває один із core Twee speaking use cases.',
      skill:'Speaking',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=discussion-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=discussion-questions'
    },
    {
      id:'sentence-list-lab',
      toolId:'v3',
      icon:'📋',
      accent:'linear-gradient(145deg,#ffaf73,#f08d54)',
      title:'Sentence List',
      eyebrow:'§ vocabulary builder',
      subtitle:'Target Vocabulary · Local Mode',
      desc:'Створює список прикладових речень з вашою лексикою, щоб швидко будувати контекст, drills і подальші gap-fill вправи.',
      skill:'Vocabulary',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=sentence-list&embed=1',
      rawUrl:'games/twee-module-studio.html?module=sentence-list'
    },
    {
      id:'gap-lab',
      toolIds:['v4','g1'],
      icon:'✏️',
      accent:'linear-gradient(145deg,#ef8d9a,#dc6a79)',
      title:'Fill in the Gap',
      eyebrow:'§ grammar + vocabulary',
      subtitle:'Gap Exercise · Local Mode',
      desc:'Будує gap-fill вправу з тексту і word bank. Працює і як vocabulary recall, і як grammar/tense adaptation inside TeachedOS.',
      skill:'Grammar',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=fill-gap&embed=1',
      rawUrl:'games/twee-module-studio.html?module=fill-gap'
    },
    {
      id:'cefr-lab',
      toolId:'u1',
      icon:'📊',
      accent:'linear-gradient(145deg,#a9b5c4,#7f8a98)',
      title:'CEFR Checker',
      eyebrow:'§ utility module',
      subtitle:'Rough Level Estimate · Local Mode',
      desc:'Дає швидку локальну CEFR-оцінку тексту і показує, чому модуль схиляється до певного рівня.',
      skill:'Utility',
      mode:'Analyze',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=cefr-checker&embed=1',
      rawUrl:'games/twee-module-studio.html?module=cefr-checker'
    },
    {
      id:'writing-prompts-lab',
      toolId:'w1',
      icon:'✍️',
      accent:'linear-gradient(145deg,#88d7a4,#6bc18a)',
      title:'Writing Prompts',
      eyebrow:'§ writing generator',
      subtitle:'Prompt Set · Local Mode',
      desc:'Створює writing prompts у стилі Twee workflow: швидкий набір тем і задач для classwork, homework або exam practice.',
      skill:'Writing',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=writing-prompts&embed=1',
      rawUrl:'games/twee-module-studio.html?module=writing-prompts'
    },
    {
      id:'dialogue-lab',
      toolId:'w2',
      icon:'💬',
      accent:'linear-gradient(145deg,#79d0dd,#59b3c5)',
      title:'Dialogue Creator',
      eyebrow:'§ writing + speaking',
      subtitle:'Dialogue Draft · Local Mode',
      desc:'Генерує короткий діалог між двома ролями на тему. Корисно для reading aloud, role-play і lesson scaffolding.',
      skill:'Writing',
      mode:'Generate',
      audience:'A1–C1',
      embedUrl:'games/twee-module-studio.html?module=dialogue-creator&embed=1',
      rawUrl:'games/twee-module-studio.html?module=dialogue-creator'
    },
    {
      id:'roleplay-lab',
      toolId:'s2',
      icon:'🎭',
      accent:'linear-gradient(145deg,#c08bff,#a96ff5)',
      title:'Role-Play Scenarios',
      eyebrow:'§ speaking pair work',
      subtitle:'Scenario Cards · Local Mode',
      desc:'Створює speaking scenario з ролями та цілями. Це природне продовження Twee-style speaking tools у нашій OS.',
      skill:'Speaking',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=role-play&embed=1',
      rawUrl:'games/twee-module-studio.html?module=role-play'
    },
    {
      id:'error-correction-lab',
      toolId:'g3',
      icon:'🔧',
      accent:'linear-gradient(145deg,#ff9d87,#ef7b67)',
      title:'Error Correction',
      eyebrow:'§ grammar accuracy',
      subtitle:'Correction Drill · Local Mode',
      desc:'Генерує набір речень з помилками для correction work. Добре працює як accuracy drill після grammar input.',
      skill:'Grammar',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=error-correction&embed=1',
      rawUrl:'games/twee-module-studio.html?module=error-correction'
    }
  ],
  curriculum: [
    {
      id:'curr-articles',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Articles: a, an, the',
      desc:'The biggest challenge for Slavic speakers — English has three articles where Russian, Ukrainian and Polish have none. Master when to use each one.',
      level:'A2',
      duration:'30 min',
      progress:72,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:1 }
    },
    {
      id:'curr-tenses',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'English Tenses vs. Slavic Aspect',
      desc:'Why English has 12 tenses but Slavic languages use aspect. Map your intuition to the English tense system and compare completed vs ongoing action.',
      level:'B1',
      duration:'45 min',
      progress:48,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:3 }
    },
    {
      id:'curr-phrasal',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'Phrasal Verbs: get, make, take, do',
      desc:'The four most essential phrasal verb families in everyday English. Learn them in context and turn them into a review note set.',
      level:'B1',
      duration:'35 min',
      progress:90,
      langs:['ru','ua','pl'],
      category:'vocab',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-prepositions',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Prepositions: at / in / on',
      desc:'English prepositions do not map cleanly to Slavic patterns. Build a short classroom summary and example bank for place and time use.',
      level:'A2',
      duration:'25 min',
      progress:100,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-order',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',
      title:'Word Order: No Flexibility',
      desc:'In English, sentence structure is fixed. Use this section to build a quick remediation note with good and bad examples.',
      level:'A2',
      duration:'20 min',
      progress:35,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'tool', target:'g3' }
    },
    {
      id:'curr-false-friends',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'False Friends: RU/UA/PL → EN',
      desc:'«Магазин» is not a magazine. «Фабрика» is not a fabric. The most dangerous false cognates for Slavic speakers.',
      level:'B1',
      duration:'30 min',
      progress:0,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'note', noteId:2 }
    },
    {
      id:'curr-speaking-prompts',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Speaking',
      title:'Discussion Starters for Class',
      desc:'Generate warm-up prompts, discussion loops, and short pair-work questions to move from passive vocabulary into active speaking.',
      level:'A2–B2',
      duration:'15 min',
      progress:15,
      langs:['ru','ua','pl'],
      category:'speaking',
      kind:'lesson',
      action:{ type:'tool', target:'s1' }
    },
    {
      id:'curr-game-match',
      track:'🎮 Interactive Lab · Vocabulary',
      title:'Word-Definition Matching',
      desc:'Interactive matching grid for vocabulary review. Great as a warm-up, station activity, or quick recap inside the OS window system.',
      level:'A2',
      duration:'Game',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'match-lab' }
    },
    {
      id:'curr-game-quiz',
      track:'🎮 Interactive Lab · Reading',
      title:'ABCD Questions from Text',
      desc:'Paste a text and generate a lightweight reading quiz inside the app. Useful for instant comprehension checks in class.',
      level:'A2–C2',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'quiz-lab' }
    },
    {
      id:'curr-game-opinions',
      track:'🎮 Interactive Lab · Speaking',
      title:'Four Opinions Generator',
      desc:'Launch the speaking module and get four contrasting opinions for pair work, debate practice, or discussion circles.',
      level:'A1–C1',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'opinions-lab' }
    },

    /* ═══════════════════════════ GRAMMAR PACK ═══════════════════════════ */
    { id:'g-be-a1',          track:'🟢 A1 · Foundations',     title:'Verb "to be" — am / is / are',        desc:'The most fundamental English verb. Build affirmative, negative, and question forms with plenty of model sentences.',                                            level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-have-a1',        track:'🟢 A1 · Foundations',     title:'Verb "to have" — have / has',         desc:'Possession and basic descriptions. Cover have got vs have, contractions, and short answers.',                                                              level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pronouns-a1',    track:'🟢 A1 · Foundations',     title:'Personal & Possessive Pronouns',      desc:'I/you/he/she/it/we/they plus my/your/his/her. Quick reference table with example pairs and common pitfalls.',                                              level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-presimp-a1',     track:'🟢 A1 · Foundations',     title:'Present Simple — routines & facts',   desc:'Daily routines, habits, and general truths. Master the 3rd-person -s/-es rule and Do/Does questions.',                                                     level:'A1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-prescon-a1',     track:'🟢 A1 · Foundations',     title:'Present Continuous — happening now',  desc:'am/is/are + V-ing for actions happening at the moment. Compare with Present Simple — a classic confusion for Slavic learners.',                            level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-thereis-a1',     track:'🟢 A1 · Foundations',     title:'There is / There are',                 desc:'Existence and location. Practice with rooms, cities, and pictures — perfect for low-level speaking warm-ups.',                                                level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastsimp-a2',    track:'🟡 A2 · Building blocks', title:'Past Simple — regular verbs',         desc:'-ed endings (worked / lived / studied) plus pronunciation rules (/t/ /d/ /ɪd/). Yesterday, last week, ago.',                                                level:'A2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastirr-a2',     track:'🟡 A2 · Building blocks', title:'Past Simple — irregular verbs',       desc:'Top-50 irregular verbs your students will actually use. Memorisation tactics and minimal-pair drills.',                                                     level:'A2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-fut-a2',         track:'🟡 A2 · Building blocks', title:'Future — will vs going to',           desc:'Plans, predictions, decisions made on the spot. Side-by-side comparison with timeline visuals.',                                                          level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-comp-a2',        track:'🟡 A2 · Building blocks', title:'Comparatives & Superlatives',         desc:'Bigger, the biggest, more interesting, the most interesting. Cover spelling rules and irregular forms (good/better/best).',                                level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-modals-a2',      track:'🟡 A2 · Building blocks', title:'Modal Verbs — can / must / should',   desc:'Ability, obligation, advice. Practice meaning differences with realistic mini-dialogues.',                                                                  level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-presperf-b1',    track:'🔵 B1 · Intermediate',    title:'Present Perfect — have / has + V3',   desc:'Experience, recent past, unfinished time periods. The classic English-vs-Slavic mismatch — give it the time it deserves.',                                  level:'B1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastcon-b1',     track:'🔵 B1 · Intermediate',    title:'Past Continuous — was / were + V-ing', desc:'Background actions, interrupted actions. Pairs naturally with Past Simple in storytelling.',                                                              level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond1-b1',       track:'🔵 B1 · Intermediate',    title:'First Conditional — if + present, will', desc:'Real possibilities and consequences. Tie it to plans, warnings, and offers your students need every week.',                                                level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-passive-b1',     track:'🔵 B1 · Intermediate',    title:'Passive Voice — basic forms',         desc:'be + past participle in Present, Past, and Future. Newspaper-headline practice works wonderfully.',                                                          level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond2-b2',       track:'🟠 B2 · Upper-intermediate', title:'Second Conditional — hypothetical', desc:'If I were you… Imaginary present and unlikely futures. Build through advice-giving scenarios.',                                                            level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond3-b2',       track:'🟠 B2 · Upper-intermediate', title:'Third Conditional — past regret',  desc:'If I had known… Talking about unreal past. Pair with regret/criticism mini-dialogues.',                                                                    level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-reported-b2',    track:'🟠 B2 · Upper-intermediate', title:'Reported Speech — backshift',     desc:'Tense, pronoun, and time-expression shifts when reporting what someone said. Common pitfalls covered.',                                                      level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-relative-b2',    track:'🟠 B2 · Upper-intermediate', title:'Relative Clauses — who / which / that / whose', desc:'Defining vs non-defining clauses, when commas matter, and when to drop the relative pronoun.',                                                        level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-gerinf-b2',      track:'🟠 B2 · Upper-intermediate', title:'Gerunds vs Infinitives',          desc:'enjoy doing vs want to do. Pattern lists by verb plus the few verbs that change meaning (remember/forget/stop).',                                          level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-mixed-c1',       track:'🔴 C1 · Advanced',        title:'Mixed Conditionals',                   desc:'Cross-time conditionals (If I had studied, I would have a better job today). Where the third meets the second.',                                              level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-inversion-c1',   track:'🔴 C1 · Advanced',        title:'Inversion — formal emphasis',          desc:'Never have I seen… Hardly had I left… Use for advanced writing tasks and formal speech.',                                                                  level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cleft-c1',       track:'🔴 C1 · Advanced',        title:'Cleft Sentences — It was / What I',    desc:'Emphasising a specific element of the sentence. Useful for journalistic and persuasive writing.',                                                            level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-subjunctive-c1', track:'🔴 C1 · Advanced',        title:'Subjunctive — were / be / suggest that', desc:'I wish I were… It is essential that he be… The rare-but-elegant subjunctive in modern English.',                                                          level:'C1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ VOCAB PACK ═══════════════════════════ */
    { id:'v-family-a1',      track:'🟢 A1 · Survival Vocab',  title:'Family & Friends',                     desc:'Mother, father, sister, brother, cousin, best friend. Build a family-tree poster as a final task.',                                                          level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'v1' } },
    { id:'v-numbers-a1',     track:'🟢 A1 · Survival Vocab',  title:'Numbers 1–100 + phone/age',           desc:'Cardinal numbers in groups (1–20, 20–100), plus how to give phone numbers and age in conversation.',                                                       level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-colors-a1',      track:'🟢 A1 · Survival Vocab',  title:'Colors & basic descriptions',         desc:'Primary and secondary colors, plus adjective placement (the red car, not the car red).',                                                                   level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-time-a1',        track:'🟢 A1 · Survival Vocab',  title:'Days, Months, Telling Time',          desc:'On Monday, in July, at 5 o\'clock. Cover prepositions of time and clock-reading conventions.',                                                              level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-food-a2',        track:'🟡 A2 · Everyday Vocab',  title:'Food & Drinks',                        desc:'Breakfast, lunch, dinner items + restaurant phrases (I would like…, Can I have…?).',                                                                       level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'v1' } },
    { id:'v-house-a2',       track:'🟡 A2 · Everyday Vocab',  title:'House & Furniture',                    desc:'Rooms of a house, furniture, household items. Pair with "There is / There are" practice.',                                                                  level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-body-a2',        track:'🟡 A2 · Everyday Vocab',  title:'Body Parts & Common Ailments',         desc:'Head, arm, leg, stomach + "I have a headache / sore throat". Useful before any travel block.',                                                              level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-clothes-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Clothes & Shopping',                   desc:'T-shirt, trousers, dress + sizes, colours, "How much is it?". Shop role-play ready.',                                                                      level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-weather-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Weather & Seasons',                    desc:'Sunny, rainy, snowy + "What\'s the weather like?". Daily forecast reading practice included.',                                                              level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-animals-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Animals — pets, farm, wild',           desc:'Common animals organised by type. Fun classifier game (mammal/bird/reptile/insect) included.',                                                              level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-jobs-b1',        track:'🔵 B1 · Topical Vocab',   title:'Jobs & Professions',                  desc:'Doctor, engineer, accountant + "What does she do? She works as…". Includes interview Q&A.',                                                                  level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-travel-b1',      track:'🔵 B1 · Topical Vocab',   title:'Travel & Holiday',                     desc:'Airport, hotel, customs, sightseeing. Add a role-play check-in and ordering at a café.',                                                                   level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-shopping-b1',    track:'🔵 B1 · Topical Vocab',   title:'Shopping & Money',                     desc:'Discounts, refunds, payment methods. "Can I pay by card?" / "Do you accept returns?".',                                                                    level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-health-b2',      track:'🟠 B2 · Topical Vocab',   title:'Health & Medicine',                    desc:'Symptoms, treatments, appointments. Practice with a doctor-patient dialogue and a pharmacy scenario.',                                                       level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-tech-b2',        track:'🟠 B2 · Topical Vocab',   title:'Technology & Internet',                desc:'App, cloud, browser, password, AI. Modern vocabulary your students see every day online.',                                                                  level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-business-b2',    track:'🟠 B2 · Topical Vocab',   title:'Business English Essentials',          desc:'Meetings, emails, deadlines, KPIs. Cover formal vs informal register and common collocations.',                                                              level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-environment-b2', track:'🟠 B2 · Topical Vocab',   title:'Environment & Climate',                desc:'Pollution, recycling, renewable energy, carbon footprint. A modern essay-writing block.',                                                                  level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-idioms-c1',      track:'🔴 C1 · Advanced Vocab',  title:'Top 30 Everyday Idioms',               desc:'Hit the books, piece of cake, under the weather. Real-world idioms native speakers actually use.',                                                          level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-collocations-c1',track:'🔴 C1 · Advanced Vocab',  title:'High-impact Collocations',             desc:'Make a decision (not do), take a shower (not make), strong coffee (not powerful). Train the right combinations.',                                          level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ MISTAKES PACK ═══════════════════════════ */
    { id:'m-articles-a2',    track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'A vs The — when each one is needed', desc:'A car (any car) vs The car (the specific one). Drill the most common Slavic-learner mistake.',                                                            level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-plurals-a1',     track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Plurals — when to add -s',           desc:'Children, men, women, feet, teeth. Plus uncountables that look plural to Slavic learners (information, advice, news).',                                  level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-questions-a2',   track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Question Formation',                 desc:'Do / Does / Did + subject + verb. Why English uses auxiliary verbs and Slavic languages don\'t.',                                                          level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-negative-a1',    track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Negatives — no double negatives',    desc:'"I don\'t know nothing" — wrong! English uses one negative per clause. Common Slavic-speaker pitfall.',                                                     level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-stress-a2',      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Word Stress — re-CORD vs RE-cord',    desc:'Same spelling, different stress, different meaning. Master noun-verb stress shifts and word families.',                                                    level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-thth-a1',        track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Pronouncing TH — /θ/ and /ð/',        desc:'Think, thing, this, that. The sound that doesn\'t exist in Slavic languages — full pronunciation drill.',                                                  level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ SPEAKING & WRITING ═══════════════════════════ */
    { id:'s-routine-a1',     track:'🗣 Speaking · Daily Life', title:'My Daily Routine',                    desc:'I wake up at 7, I have breakfast, I go to work. Build a speaking model + record yourself task.',                                                            level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-describe-a2',    track:'🗣 Speaking · Daily Life', title:'Describing People',                   desc:'Tall, short, blonde, curly hair. Personality adjectives (kind, shy, outgoing). Pair description game.',                                                    level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-hobbies-a2',     track:'🗣 Speaking · Daily Life', title:'My Hobbies & Free Time',              desc:'I like / I love / I hate + V-ing. Build a 1-minute monologue every student can deliver confidently.',                                                      level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-story-b1',       track:'🗣 Speaking · Storytelling', title:'Tell a Story — Past Tenses',       desc:'Once upon a time… Sequencing words (first, then, after that, finally) with Past Simple + Continuous.',                                                       level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-opinion-b2',     track:'🗣 Speaking · Discussion', title:'Giving Opinions & Arguments',         desc:'In my opinion / I believe / On the other hand. Structure for B2-style discussion and debate.',                                                                level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'s-debate-c1',      track:'🗣 Speaking · Discussion', title:'Formal Debate Structures',            desc:'Opening, rebuttal, summary. Set up a full classroom debate with prep cards and timing rules.',                                                              level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'w-email-b2',       track:'✍️ Writing · Formal',     title:'Formal & Informal Emails',             desc:'Dear Mr. Smith vs Hi John. Cover greetings, sign-offs, register, and three common email types (request / apology / inquiry).', level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'w-essay-c1',       track:'✍️ Writing · Academic',   title:'Opinion Essay — 4 paragraphs',         desc:'Intro, two body paragraphs (for/against), conclusion. Plus phrases that lift the band score.',                                                              level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },

    /* ═══════════════════════════ READING & LISTENING ═══════════════════════════ */
    { id:'r-shortstory-a2',  track:'📖 Reading · Stories',     title:'Short Story Comprehension',           desc:'Adapted A2-level story + pre-reading vocab, true/false, and open questions. Drop-in ready.',                                                                level:'A2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'r-news-b1',        track:'📖 Reading · News',        title:'News Article Comprehension',          desc:'Modern news article + glossary, ABCD quiz, and discussion questions. Always feels fresh.',                                                                  level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'r-academic-c1',    track:'📖 Reading · Academic',    title:'Academic Text — Critical Reading',    desc:'C1-level passage + inference questions, paraphrase practice, and a writing follow-up.',                                                                    level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'l-podcast-b2',     track:'🎧 Listening · Podcasts',  title:'Podcast Snippet — Note-taking',       desc:'Short podcast clip + comprehension grid, gap-fill transcript, and follow-up discussion questions.',                                                          level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l1' } }
  ]
};
