window.TEACHEDOS_DATA = {
  tools: [
    { id:'r1', name:'Create a Text on Any Topic with Your Vocabulary', desc:'Paste a topic and a word list to generate a CEFR-friendly text. Great for reading work, homework, or a custom lead-in after a vocabulary lesson.', tags:['Reading','Vocabulary'], badge:null, icon:'📄', group:'reading' },
    { id:'r2', name:'Create ABCD Questions', desc:'Локальний модуль створює multiple-choice запитання з тексту прямо на GitHub Pages без API-ключа. Зручно для швидких reading quizzes.', tags:['Reading'], badge:'New', icon:'🔡', group:'reading' },
    { id:'r3', name:'Create Open Questions', desc:'Produces open-ended comprehension questions that encourage critical thinking and discussion around the text.', tags:['Reading'], badge:null, icon:'❓', group:'reading' },
    { id:'r4', name:'Create True/False Statements', desc:'Creates a true/false reading exercise to quickly check if students understood the key facts and details of the text.', tags:['Reading'], badge:'Pro', icon:'✅', group:'reading' },
    { id:'w1', name:'Writing Prompts', desc:'Generates creative or structured writing prompts tailored to a specific topic and CEFR level — useful for class writing, homework, and exam-style warm-ups.', tags:['Writing'], badge:'New', icon:'✍️', group:'writing' },
    { id:'w2', name:'Dialogue Creator', desc:'Creates a short dialogue between two characters on any topic and level. Use for reading, comprehension, or role-play speaking practice.', tags:['Writing','Speaking'], badge:'New', icon:'💬', group:'writing' },
    { id:'l1', name:'Audio & Video Question Creator', desc:'Upload any audio or video file and auto-generate open questions, multiple-choice questions, or true/false statements based on the content.', tags:['Listening'], badge:'Pro', icon:'🎙️', group:'listening' },
    { id:'l2', name:'Convert Audio & Video to Text', desc:'Transcribes mp3, mp4, or YouTube links into a readable transcript ready for classroom use as a reading or gap-fill activity.', tags:['Listening'], badge:'Pro', icon:'🎬', group:'listening' },
    { id:'s1', name:'Find Discussion Questions', desc:'Creates engaging discussion questions on any topic — use as a warm-up, while-lesson discussion, or speaking fluency practice for any level.', tags:['Speaking'], badge:null, icon:'🗣️', group:'speaking' },
    { id:'s2', name:'Role-Play Scenarios', desc:'Generates role-play cards and scenario prompts for pair or group speaking activities. Set the context and get ready-to-use speaking tasks.', tags:['Speaking'], badge:'New', icon:'🎭', group:'speaking' },
    { id:'s3', name:'Four Opinions Generator', desc:'Генерує 4 різні англомовні позиції за темою, рівнем і довжиною. Добре працює як speaking warm-up або debate starter.', tags:['Speaking'], badge:'New', icon:'🧠', group:'speaking' },
    { id:'v1', name:'Word-Image Matching', desc:'Creates a vocabulary exercise where students match each word to the correct picture. Boosts visual recognition and word retention.', tags:['Vocabulary'], badge:'New', icon:'🖼️', group:'vocabulary' },
    { id:'v2', name:'Word-Definition Matching', desc:'Інтерактивна гра на співставлення слова з визначенням. Перекладено українською та вбудовано прямо в TeachedOS.', tags:['Vocabulary'], badge:'New', icon:'🔍', group:'vocabulary' },
    { id:'v3', name:'Create a List of Sentences with Your Vocabulary', desc:'Generates example sentences using your target vocabulary list. Great before a Fill-in-the-Gap task or as a quick context bank for a new word set.', tags:['Vocabulary'], badge:'Pro', icon:'📋', group:'vocabulary' },
    { id:'v4', name:'Fill in the Gap', desc:'Replaces chosen words in a text with blank gaps and provides the word list separately. Works for vocabulary recall and grammar tense practice.', tags:['Vocabulary','Grammar'], badge:null, icon:'✏️', group:'vocabulary' },
    { id:'g1', name:'Fill in the Gap', desc:'Replaces chosen words in a text with gaps. Add verb forms or tense markers to turn it into a grammar tense or form exercise.', tags:['Grammar','Vocabulary'], badge:null, icon:'✏️', group:'grammar' },
    { id:'g2', name:'Grammar Worksheets', desc:'Generates structured grammar worksheets with clear explanations, examples, and progressive exercises for any grammar point and CEFR level.', tags:['Grammar'], badge:null, icon:'📑', group:'grammar' },
    { id:'g3', name:'Error Correction', desc:'Creates sentences with intentional grammar or vocabulary mistakes for students to identify and fix. Great for proofreading and accuracy tasks.', tags:['Grammar'], badge:'New', icon:'🔧', group:'grammar' },
    { id:'u1', name:'CEFR Level Checker', desc:'Paste any text and instantly determine its CEFR proficiency level (A1–C2) according to the Common European Framework of Reference.', tags:['Utility'], badge:'Pro', icon:'📊', group:'utility' },
    { id:'u2', name:'Lesson Plan Generator', desc:'Input a topic, level, and lesson duration — get a complete, structured lesson plan with objectives, activities, and timing suggestions.', tags:['Utility'], badge:null, icon:'📅', group:'utility' }
  ],
  games: [
    {
      id:'quiz-lab',
      toolId:'r2',
      icon:'🔡',
      accent:'linear-gradient(145deg,#7ca8ff,#356dff)',
      title:'LinguaQuiz AI',
      eyebrow:'§ reading generator',
      subtitle:'ABCD Questions · Local Mode',
      desc:'Локальний модуль для reading practice: вставляєте текст і отримуєте multiple-choice питання прямо у вікні OS без API-ключів і зовнішнього бекенду.',
      skill:'Reading',
      mode:'Offline',
      audience:'A1–C2',
      embedUrl:'games/linguaquiz-ai-uk.html?embed=1',
      rawUrl:'games/linguaquiz-ai-uk.html'
    },
    {
      id:'opinions-lab',
      toolId:'s3',
      icon:'🧠',
      accent:'linear-gradient(145deg,#b687ff,#7f56e3)',
      title:'Four Opinions Generator',
      eyebrow:'§ speaking starter',
      subtitle:'Debate Module · Four Voices',
      desc:'Органічний speaking-модуль для warm-up, pair work та discussion circles. Створює чотири контрастні точки зору англійською в компактному системному режимі.',
      skill:'Speaking',
      mode:'Offline',
      audience:'A1–C1',
      embedUrl:'games/four-opinions-uk.html?embed=1',
      rawUrl:'games/four-opinions-uk.html'
    },
    {
      id:'match-lab',
      toolId:'v2',
      icon:'🔍',
      accent:'linear-gradient(145deg,#ff9a62,#d96b2b)',
      title:'Word-Definition Matching',
      eyebrow:'§ vocabulary module',
      subtitle:'Matching Grid · Embedded',
      desc:'Інтерактивна вправа на співставлення слів і визначень. Перекладена українською і підготовлена як повноцінний модуль TeachedOS, а не окрема сторінка.',
      skill:'Vocabulary',
      mode:'Playable',
      audience:'A2–B2',
      embedUrl:'games/word-definition-match.html?embed=1',
      rawUrl:'games/word-definition-match.html'
    },
    {
      id:'text-builder-lab',
      toolId:'r1',
      icon:'📄',
      accent:'linear-gradient(145deg,#7ca8ff,#4567f4)',
      title:'Text Builder',
      eyebrow:'§ reading generator',
      subtitle:'Topic + Vocabulary · Local Mode',
      desc:'Генерує короткий текст на тему з вашою лексикою і рівнем CEFR. Це наш локальний аналог одного з базових Twee reading modules.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C1',
      embedUrl:'games/twee-module-studio.html?module=text-vocab&embed=1',
      rawUrl:'games/twee-module-studio.html?module=text-vocab'
    },
    {
      id:'open-questions-lab',
      toolId:'r3',
      icon:'❓',
      accent:'linear-gradient(145deg,#84b8ff,#4d91ff)',
      title:'Open Questions',
      eyebrow:'§ reading check',
      subtitle:'Comprehension Questions · Local Mode',
      desc:'Створює відкриті питання до тексту у стилі Twee workflow: швидко, локально і без зовнішніх сервісів.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=open-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=open-questions'
    },
    {
      id:'true-false-lab',
      toolId:'r4',
      icon:'✅',
      accent:'linear-gradient(145deg,#6ed39c,#4fb58b)',
      title:'True / False',
      eyebrow:'§ reading exercise',
      subtitle:'Statement Builder · Local Mode',
      desc:'Генерує true/false вправу на основі тексту. Підходить для короткої comprehension check activity після reading.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=true-false&embed=1',
      rawUrl:'games/twee-module-studio.html?module=true-false'
    },
    {
      id:'discussion-lab',
      toolId:'s1',
      icon:'🗣️',
      accent:'linear-gradient(145deg,#bb8cff,#8f61f1)',
      title:'Discussion Questions',
      eyebrow:'§ speaking warm-up',
      subtitle:'Topic Prompts · Local Mode',
      desc:'Підбирає discussion questions на тему для warm-up, pair work або freer speaking. Органічно закриває один із core Twee speaking use cases.',
      skill:'Speaking',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=discussion-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=discussion-questions'
    },
    {
      id:'sentence-list-lab',
      toolId:'v3',
      icon:'📋',
      accent:'linear-gradient(145deg,#ffaf73,#f08d54)',
      title:'Sentence List',
      eyebrow:'§ vocabulary builder',
      subtitle:'Target Vocabulary · Local Mode',
      desc:'Створює список прикладових речень з вашою лексикою, щоб швидко будувати контекст, drills і подальші gap-fill вправи.',
      skill:'Vocabulary',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=sentence-list&embed=1',
      rawUrl:'games/twee-module-studio.html?module=sentence-list'
    },
    {
      id:'gap-lab',
      toolIds:['v4','g1'],
      icon:'✏️',
      accent:'linear-gradient(145deg,#ef8d9a,#dc6a79)',
      title:'Fill in the Gap',
      eyebrow:'§ grammar + vocabulary',
      subtitle:'Gap Exercise · Local Mode',
      desc:'Будує gap-fill вправу з тексту і word bank. Працює і як vocabulary recall, і як grammar/tense adaptation inside TeachedOS.',
      skill:'Grammar',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=fill-gap&embed=1',
      rawUrl:'games/twee-module-studio.html?module=fill-gap'
    },
    {
      id:'cefr-lab',
      toolId:'u1',
      icon:'📊',
      accent:'linear-gradient(145deg,#a9b5c4,#7f8a98)',
      title:'CEFR Checker',
      eyebrow:'§ utility module',
      subtitle:'Rough Level Estimate · Local Mode',
      desc:'Дає швидку локальну CEFR-оцінку тексту і показує, чому модуль схиляється до певного рівня.',
      skill:'Utility',
      mode:'Analyze',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=cefr-checker&embed=1',
      rawUrl:'games/twee-module-studio.html?module=cefr-checker'
    },
    {
      id:'writing-prompts-lab',
      toolId:'w1',
      icon:'✍️',
      accent:'linear-gradient(145deg,#88d7a4,#6bc18a)',
      title:'Writing Prompts',
      eyebrow:'§ writing generator',
      subtitle:'Prompt Set · Local Mode',
      desc:'Створює writing prompts у стилі Twee workflow: швидкий набір тем і задач для classwork, homework або exam practice.',
      skill:'Writing',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=writing-prompts&embed=1',
      rawUrl:'games/twee-module-studio.html?module=writing-prompts'
    },
    {
      id:'dialogue-lab',
      toolId:'w2',
      icon:'💬',
      accent:'linear-gradient(145deg,#79d0dd,#59b3c5)',
      title:'Dialogue Creator',
      eyebrow:'§ writing + speaking',
      subtitle:'Dialogue Draft · Local Mode',
      desc:'Генерує короткий діалог між двома ролями на тему. Корисно для reading aloud, role-play і lesson scaffolding.',
      skill:'Writing',
      mode:'Generate',
      audience:'A1–C1',
      embedUrl:'games/twee-module-studio.html?module=dialogue-creator&embed=1',
      rawUrl:'games/twee-module-studio.html?module=dialogue-creator'
    },
    {
      id:'roleplay-lab',
      toolId:'s2',
      icon:'🎭',
      accent:'linear-gradient(145deg,#c08bff,#a96ff5)',
      title:'Role-Play Scenarios',
      eyebrow:'§ speaking pair work',
      subtitle:'Scenario Cards · Local Mode',
      desc:'Створює speaking scenario з ролями та цілями. Це природне продовження Twee-style speaking tools у нашій OS.',
      skill:'Speaking',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=role-play&embed=1',
      rawUrl:'games/twee-module-studio.html?module=role-play'
    },
    {
      id:'error-correction-lab',
      toolId:'g3',
      icon:'🔧',
      accent:'linear-gradient(145deg,#ff9d87,#ef7b67)',
      title:'Error Correction',
      eyebrow:'§ grammar accuracy',
      subtitle:'Correction Drill · Local Mode',
      desc:'Генерує набір речень з помилками для correction work. Добре працює як accuracy drill після grammar input.',
      skill:'Grammar',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=error-correction&embed=1',
      rawUrl:'games/twee-module-studio.html?module=error-correction'
    }
  ],
  curriculum: [
    {
      id:'curr-articles',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Articles: a, an, the',
      desc:'The biggest challenge for Slavic speakers — English has three articles where Russian, Ukrainian and Polish have none. Master when to use each one.',
      level:'A2',
      duration:'30 min',
      progress:72,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:1 }
    },
    {
      id:'curr-tenses',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'English Tenses vs. Slavic Aspect',
      desc:'Why English has 12 tenses but Slavic languages use aspect. Map your intuition to the English tense system and compare completed vs ongoing action.',
      level:'B1',
      duration:'45 min',
      progress:48,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:3 }
    },
    {
      id:'curr-phrasal',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'Phrasal Verbs: get, make, take, do',
      desc:'The four most essential phrasal verb families in everyday English. Learn them in context and turn them into a review note set.',
      level:'B1',
      duration:'35 min',
      progress:90,
      langs:['ru','ua','pl'],
      category:'vocab',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-prepositions',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Prepositions: at / in / on',
      desc:'English prepositions do not map cleanly to Slavic patterns. Build a short classroom summary and example bank for place and time use.',
      level:'A2',
      duration:'25 min',
      progress:100,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-order',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',
      title:'Word Order: No Flexibility',
      desc:'In English, sentence structure is fixed. Use this section to build a quick remediation note with good and bad examples.',
      level:'A2',
      duration:'20 min',
      progress:35,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'tool', target:'g3' }
    },
    {
      id:'curr-false-friends',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'False Friends: RU/UA/PL → EN',
      desc:'«Магазин» is not a magazine. «Фабрика» is not a fabric. The most dangerous false cognates for Slavic speakers.',
      level:'B1',
      duration:'30 min',
      progress:0,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'note', noteId:2 }
    },
    {
      id:'curr-speaking-prompts',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Speaking',
      title:'Discussion Starters for Class',
      desc:'Generate warm-up prompts, discussion loops, and short pair-work questions to move from passive vocabulary into active speaking.',
      level:'A2–B2',
      duration:'15 min',
      progress:15,
      langs:['ru','ua','pl'],
      category:'speaking',
      kind:'lesson',
      action:{ type:'tool', target:'s1' }
    },
    {
      id:'curr-game-match',
      track:'🎮 Interactive Lab · Vocabulary',
      title:'Word-Definition Matching',
      desc:'Interactive matching grid for vocabulary review. Great as a warm-up, station activity, or quick recap inside the OS window system.',
      level:'A2',
      duration:'Game',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'match-lab' }
    },
    {
      id:'curr-game-quiz',
      track:'🎮 Interactive Lab · Reading',
      title:'ABCD Questions from Text',
      desc:'Paste a text and generate a lightweight reading quiz inside the app. Useful for instant comprehension checks in class.',
      level:'A2–C2',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'quiz-lab' }
    },
    {
      id:'curr-game-opinions',
      track:'🎮 Interactive Lab · Speaking',
      title:'Four Opinions Generator',
      desc:'Launch the speaking module and get four contrasting opinions for pair work, debate practice, or discussion circles.',
      level:'A1–C1',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'opinions-lab' }
    },

    /* ═══════════════════════════ GRAMMAR PACK ═══════════════════════════ */
    { id:'g-be-a1',          track:'🟢 A1 · Foundations',     title:'Verb "to be" — am / is / are',        desc:'The most fundamental English verb. Build affirmative, negative, and question forms with plenty of model sentences.',                                            level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-have-a1',        track:'🟢 A1 · Foundations',     title:'Verb "to have" — have / has',         desc:'Possession and basic descriptions. Cover have got vs have, contractions, and short answers.',                                                              level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pronouns-a1',    track:'🟢 A1 · Foundations',     title:'Personal & Possessive Pronouns',      desc:'I/you/he/she/it/we/they plus my/your/his/her. Quick reference table with example pairs and common pitfalls.',                                              level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-presimp-a1',     track:'🟢 A1 · Foundations',     title:'Present Simple — routines & facts',   desc:'Daily routines, habits, and general truths. Master the 3rd-person -s/-es rule and Do/Does questions.',                                                     level:'A1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-prescon-a1',     track:'🟢 A1 · Foundations',     title:'Present Continuous — happening now',  desc:'am/is/are + V-ing for actions happening at the moment. Compare with Present Simple — a classic confusion for Slavic learners.',                            level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-thereis-a1',     track:'🟢 A1 · Foundations',     title:'There is / There are',                 desc:'Existence and location. Practice with rooms, cities, and pictures — perfect for low-level speaking warm-ups.',                                                level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastsimp-a2',    track:'🟡 A2 · Building blocks', title:'Past Simple — regular verbs',         desc:'-ed endings (worked / lived / studied) plus pronunciation rules (/t/ /d/ /ɪd/). Yesterday, last week, ago.',                                                level:'A2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastirr-a2',     track:'🟡 A2 · Building blocks', title:'Past Simple — irregular verbs',       desc:'Top-50 irregular verbs your students will actually use. Memorisation tactics and minimal-pair drills.',                                                     level:'A2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-fut-a2',         track:'🟡 A2 · Building blocks', title:'Future — will vs going to',           desc:'Plans, predictions, decisions made on the spot. Side-by-side comparison with timeline visuals.',                                                          level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-comp-a2',        track:'🟡 A2 · Building blocks', title:'Comparatives & Superlatives',         desc:'Bigger, the biggest, more interesting, the most interesting. Cover spelling rules and irregular forms (good/better/best).',                                level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-modals-a2',      track:'🟡 A2 · Building blocks', title:'Modal Verbs — can / must / should',   desc:'Ability, obligation, advice. Practice meaning differences with realistic mini-dialogues.',                                                                  level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-presperf-b1',    track:'🔵 B1 · Intermediate',    title:'Present Perfect — have / has + V3',   desc:'Experience, recent past, unfinished time periods. The classic English-vs-Slavic mismatch — give it the time it deserves.',                                  level:'B1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastcon-b1',     track:'🔵 B1 · Intermediate',    title:'Past Continuous — was / were + V-ing', desc:'Background actions, interrupted actions. Pairs naturally with Past Simple in storytelling.',                                                              level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond1-b1',       track:'🔵 B1 · Intermediate',    title:'First Conditional — if + present, will', desc:'Real possibilities and consequences. Tie it to plans, warnings, and offers your students need every week.',                                                level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-passive-b1',     track:'🔵 B1 · Intermediate',    title:'Passive Voice — basic forms',         desc:'be + past participle in Present, Past, and Future. Newspaper-headline practice works wonderfully.',                                                          level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond2-b2',       track:'🟠 B2 · Upper-intermediate', title:'Second Conditional — hypothetical', desc:'If I were you… Imaginary present and unlikely futures. Build through advice-giving scenarios.',                                                            level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cond3-b2',       track:'🟠 B2 · Upper-intermediate', title:'Third Conditional — past regret',  desc:'If I had known… Talking about unreal past. Pair with regret/criticism mini-dialogues.',                                                                    level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-reported-b2',    track:'🟠 B2 · Upper-intermediate', title:'Reported Speech — backshift',     desc:'Tense, pronoun, and time-expression shifts when reporting what someone said. Common pitfalls covered.',                                                      level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-relative-b2',    track:'🟠 B2 · Upper-intermediate', title:'Relative Clauses — who / which / that / whose', desc:'Defining vs non-defining clauses, when commas matter, and when to drop the relative pronoun.',                                                        level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-gerinf-b2',      track:'🟠 B2 · Upper-intermediate', title:'Gerunds vs Infinitives',          desc:'enjoy doing vs want to do. Pattern lists by verb plus the few verbs that change meaning (remember/forget/stop).',                                          level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-mixed-c1',       track:'🔴 C1 · Advanced',        title:'Mixed Conditionals',                   desc:'Cross-time conditionals (If I had studied, I would have a better job today). Where the third meets the second.',                                              level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-inversion-c1',   track:'🔴 C1 · Advanced',        title:'Inversion — formal emphasis',          desc:'Never have I seen… Hardly had I left… Use for advanced writing tasks and formal speech.',                                                                  level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-cleft-c1',       track:'🔴 C1 · Advanced',        title:'Cleft Sentences — It was / What I',    desc:'Emphasising a specific element of the sentence. Useful for journalistic and persuasive writing.',                                                            level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-subjunctive-c1', track:'🔴 C1 · Advanced',        title:'Subjunctive — were / be / suggest that', desc:'I wish I were… It is essential that he be… The rare-but-elegant subjunctive in modern English.',                                                          level:'C1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ VOCAB PACK ═══════════════════════════ */
    { id:'v-family-a1',      track:'🟢 A1 · Survival Vocab',  title:'Family & Friends',                     desc:'Mother, father, sister, brother, cousin, best friend. Build a family-tree poster as a final task.',                                                          level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'v1' } },
    { id:'v-numbers-a1',     track:'🟢 A1 · Survival Vocab',  title:'Numbers 1–100 + phone/age',           desc:'Cardinal numbers in groups (1–20, 20–100), plus how to give phone numbers and age in conversation.',                                                       level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-colors-a1',      track:'🟢 A1 · Survival Vocab',  title:'Colors & basic descriptions',         desc:'Primary and secondary colors, plus adjective placement (the red car, not the car red).',                                                                   level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-time-a1',        track:'🟢 A1 · Survival Vocab',  title:'Days, Months, Telling Time',          desc:'On Monday, in July, at 5 o\'clock. Cover prepositions of time and clock-reading conventions.',                                                              level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-food-a2',        track:'🟡 A2 · Everyday Vocab',  title:'Food & Drinks',                        desc:'Breakfast, lunch, dinner items + restaurant phrases (I would like…, Can I have…?).',                                                                       level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'v1' } },
    { id:'v-house-a2',       track:'🟡 A2 · Everyday Vocab',  title:'House & Furniture',                    desc:'Rooms of a house, furniture, household items. Pair with "There is / There are" practice.',                                                                  level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-body-a2',        track:'🟡 A2 · Everyday Vocab',  title:'Body Parts & Common Ailments',         desc:'Head, arm, leg, stomach + "I have a headache / sore throat". Useful before any travel block.',                                                              level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-clothes-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Clothes & Shopping',                   desc:'T-shirt, trousers, dress + sizes, colours, "How much is it?". Shop role-play ready.',                                                                      level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-weather-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Weather & Seasons',                    desc:'Sunny, rainy, snowy + "What\'s the weather like?". Daily forecast reading practice included.',                                                              level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-animals-a2',     track:'🟡 A2 · Everyday Vocab',  title:'Animals — pets, farm, wild',           desc:'Common animals organised by type. Fun classifier game (mammal/bird/reptile/insect) included.',                                                              level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-jobs-b1',        track:'🔵 B1 · Topical Vocab',   title:'Jobs & Professions',                  desc:'Doctor, engineer, accountant + "What does she do? She works as…". Includes interview Q&A.',                                                                  level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-travel-b1',      track:'🔵 B1 · Topical Vocab',   title:'Travel & Holiday',                     desc:'Airport, hotel, customs, sightseeing. Add a role-play check-in and ordering at a café.',                                                                   level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-shopping-b1',    track:'🔵 B1 · Topical Vocab',   title:'Shopping & Money',                     desc:'Discounts, refunds, payment methods. "Can I pay by card?" / "Do you accept returns?".',                                                                    level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-health-b2',      track:'🟠 B2 · Topical Vocab',   title:'Health & Medicine',                    desc:'Symptoms, treatments, appointments. Practice with a doctor-patient dialogue and a pharmacy scenario.',                                                       level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-tech-b2',        track:'🟠 B2 · Topical Vocab',   title:'Technology & Internet',                desc:'App, cloud, browser, password, AI. Modern vocabulary your students see every day online.',                                                                  level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-business-b2',    track:'🟠 B2 · Topical Vocab',   title:'Business English Essentials',          desc:'Meetings, emails, deadlines, KPIs. Cover formal vs informal register and common collocations.',                                                              level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-environment-b2', track:'🟠 B2 · Topical Vocab',   title:'Environment & Climate',                desc:'Pollution, recycling, renewable energy, carbon footprint. A modern essay-writing block.',                                                                  level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-idioms-c1',      track:'🔴 C1 · Advanced Vocab',  title:'Top 30 Everyday Idioms',               desc:'Hit the books, piece of cake, under the weather. Real-world idioms native speakers actually use.',                                                          level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-collocations-c1',track:'🔴 C1 · Advanced Vocab',  title:'High-impact Collocations',             desc:'Make a decision (not do), take a shower (not make), strong coffee (not powerful). Train the right combinations.',                                          level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ MISTAKES PACK ═══════════════════════════ */
    { id:'m-articles-a2',    track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'A vs The — when each one is needed', desc:'A car (any car) vs The car (the specific one). Drill the most common Slavic-learner mistake.',                                                            level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-plurals-a1',     track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Plurals — when to add -s',           desc:'Children, men, women, feet, teeth. Plus uncountables that look plural to Slavic learners (information, advice, news).',                                  level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-questions-a2',   track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Question Formation',                 desc:'Do / Does / Did + subject + verb. Why English uses auxiliary verbs and Slavic languages don\'t.',                                                          level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-negative-a1',    track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Negatives — no double negatives',    desc:'"I don\'t know nothing" — wrong! English uses one negative per clause. Common Slavic-speaker pitfall.',                                                     level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-stress-a2',      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Word Stress — re-CORD vs RE-cord',    desc:'Same spelling, different stress, different meaning. Master noun-verb stress shifts and word families.',                                                    level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-thth-a1',        track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes', title:'Pronouncing TH — /θ/ and /ð/',        desc:'Think, thing, this, that. The sound that doesn\'t exist in Slavic languages — full pronunciation drill.',                                                  level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ SPEAKING & WRITING ═══════════════════════════ */
    { id:'s-routine-a1',     track:'🗣 Speaking · Daily Life', title:'My Daily Routine',                    desc:'I wake up at 7, I have breakfast, I go to work. Build a speaking model + record yourself task.',                                                            level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-describe-a2',    track:'🗣 Speaking · Daily Life', title:'Describing People',                   desc:'Tall, short, blonde, curly hair. Personality adjectives (kind, shy, outgoing). Pair description game.',                                                    level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-hobbies-a2',     track:'🗣 Speaking · Daily Life', title:'My Hobbies & Free Time',              desc:'I like / I love / I hate + V-ing. Build a 1-minute monologue every student can deliver confidently.',                                                      level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-story-b1',       track:'🗣 Speaking · Storytelling', title:'Tell a Story — Past Tenses',       desc:'Once upon a time… Sequencing words (first, then, after that, finally) with Past Simple + Continuous.',                                                       level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'s-opinion-b2',     track:'🗣 Speaking · Discussion', title:'Giving Opinions & Arguments',         desc:'In my opinion / I believe / On the other hand. Structure for B2-style discussion and debate.',                                                                level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'s-debate-c1',      track:'🗣 Speaking · Discussion', title:'Formal Debate Structures',            desc:'Opening, rebuttal, summary. Set up a full classroom debate with prep cards and timing rules.',                                                              level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'w-email-b2',       track:'✍️ Writing · Formal',     title:'Formal & Informal Emails',             desc:'Dear Mr. Smith vs Hi John. Cover greetings, sign-offs, register, and three common email types (request / apology / inquiry).', level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'w-essay-c1',       track:'✍️ Writing · Academic',   title:'Opinion Essay — 4 paragraphs',         desc:'Intro, two body paragraphs (for/against), conclusion. Plus phrases that lift the band score.',                                                              level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },

    /* ═══════════════════════════ READING & LISTENING ═══════════════════════════ */
    { id:'r-shortstory-a2',  track:'📖 Reading · Stories',     title:'Short Story Comprehension',           desc:'Adapted A2-level story + pre-reading vocab, true/false, and open questions. Drop-in ready.',                                                                level:'A2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'r-news-b1',        track:'📖 Reading · News',        title:'News Article Comprehension',          desc:'Modern news article + glossary, ABCD quiz, and discussion questions. Always feels fresh.',                                                                  level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'r-academic-c1',    track:'📖 Reading · Academic',    title:'Academic Text — Critical Reading',    desc:'C1-level passage + inference questions, paraphrase practice, and a writing follow-up.',                                                                    level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'l-podcast-b2',     track:'🎧 Listening · Podcasts',  title:'Podcast Snippet — Note-taking',       desc:'Short podcast clip + comprehension grid, gap-fill transcript, and follow-up discussion questions.',                                                          level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l1' } },

    /* ═══════════════════════════ GRAMMAR — EXTENDED ═══════════════════════════ */
    { id:'g-imperatives-a1',    track:'🟢 A1 · Foundations',        title:'Imperatives — commands & requests',          desc:'Open the book! Don\'t run! Please sit down. Simple command forms and polite softeners for classroom language.',                                          level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-adjectives-a1',     track:'🟢 A1 · Foundations',        title:'Adjectives — order & placement',             desc:'A tall young man, not a young tall man. Master the standard adjective order and avoid the most common placement errors.',                              level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-countable-a1',      track:'🟢 A1 · Foundations',        title:'Countable & Uncountable Nouns',              desc:'An apple / some water. The category mismatch that trips every Slavic learner of English at A1.',                                                       level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-questions-a1',      track:'🟢 A1 · Foundations',        title:'Question Words — Who / What / Where / When', desc:'Wh-questions from scratch. Build the habit of auxiliary-verb inversion with minimal pairs and drilling.',                                              level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-frequency-a2',      track:'🟡 A2 · Building blocks',    title:'Adverbs of Frequency',                       desc:'Always / usually / often / sometimes / rarely / never in the right position. Students often place them at the end — fix this fast.',                 level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-muchMany-a2',       track:'🟡 A2 · Building blocks',    title:'Much / Many / Some / Any / A lot of',        desc:'Much water vs many bottles. Any in questions and negatives. A lot of in affirmatives. Organised by countability.',                                     level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-tooenough-a2',      track:'🟡 A2 · Building blocks',    title:'Too / Enough',                               desc:'It\'s too hot to swim. I\'m not fit enough to run. Classic B2 gap-fill and error-correction pair.',                                                     level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-prezperfIntro-a2',  track:'🟡 A2 · Building blocks',    title:'Present Perfect — first look',               desc:'A gentle A2 intro to have + V3 for experience and the words ever/never/already/just/yet.',                                                             level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-usedto-b1',         track:'🔵 B1 · Intermediate',       title:'Used to / Would — past habits',              desc:'I used to play football vs I would play every weekend. When they\'re interchangeable and when they\'re not.',                                          level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-presperfc-b1',      track:'🔵 B1 · Intermediate',       title:'Present Perfect Continuous',                 desc:'I\'ve been studying for three hours. Duration emphasis + for/since. Contrast with Present Perfect Simple.',                                            level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-pastperf-b1',       track:'🔵 B1 · Intermediate',       title:'Past Perfect — had + V3',                    desc:'By the time she arrived, he had left. Sequence of past events in storytelling and reported speech.',                                                   level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-futcont-b1',        track:'🔵 B1 · Intermediate',       title:'Future Continuous & Future Perfect',         desc:'At 8pm I will be eating. By 9pm I will have eaten. Two future forms that feel unnatural to Slavic speakers.',                                       level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-passiveAdv-b2',     track:'🟠 B2 · Upper-intermediate', title:'Passive Voice — advanced forms',             desc:'Perfect passives (has been done), modal passives (should be done), and passive with get (got fired).',                                                level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-wish-b2',           track:'🟠 B2 · Upper-intermediate', title:'Wish / If only — regrets & wishes',          desc:'I wish I knew, If only I had studied. Map against the conditional forms students already know.',                                                     level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-participle-b2',     track:'🟠 B2 · Upper-intermediate', title:'Participle Clauses',                         desc:'Walking down the street, I saw her. Reduced relative and adverbial clauses — an elegant B2 writing upgrade.',                                            level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-soSuch-b2',         track:'🟠 B2 · Upper-intermediate', title:'So / Such / Too / Enough — advanced',        desc:'Such a beautiful city vs so beautiful. Too cold to go vs cold enough to freeze. Full pattern contrasts.',                                             level:'B2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-discourse-c1',      track:'🔴 C1 · Advanced',           title:'Discourse Markers — cohesion & flow',        desc:'Furthermore, Nevertheless, Conversely, In contrast. The linkers that separate B2 writing from C1.',                                                  level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-modal-adv-c1',      track:'🔴 C1 · Advanced',           title:'Advanced Modal Meanings',                    desc:'Must have been, can\'t have done, should have said. Past modals for deduction, criticism, and regret.',                                              level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-nominal-c1',        track:'🔴 C1 · Advanced',           title:'Nominalisation — noun-heavy style',          desc:'The arrival of the train vs The train arrived. Convert verb structures to noun phrases for academic writing.',                                        level:'C1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-ellipsis-c1',       track:'🔴 C1 · Advanced',           title:'Ellipsis & Substitution',                    desc:'I think so / I don\'t think so / so do I. What can be left out and what replaces it in natural spoken English.',                                    level:'C1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-academicGram-c2',   track:'🟣 C2 · Mastery',           title:'Academic Grammar — advanced patterns',        desc:'It is suggested that… / It has been established… Passive impersonal structures, stance markers, and hedging.',                                        level:'C2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },
    { id:'g-stylistic-c2',      track:'🟣 C2 · Mastery',           title:'Stylistic Inversion & Fronting',              desc:'Not only did she win, but she also broke the record. Fronting for emphasis in formal and literary styles.',                                            level:'C2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'grammar', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ VOCAB — EXTENDED ═══════════════════════════ */
    { id:'v-classroom-a1',      track:'🟢 A1 · Survival Vocab',    title:'Classroom Language',                         desc:'Book, pen, board, desk, lesson, homework, repeat, spell. The essential language for day one.',                                                         level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-greetings-a1',      track:'🟢 A1 · Survival Vocab',    title:'Greetings & Introductions',                  desc:'Hi / Hello / Nice to meet you / My name is / I\'m from… Build the first conversation your students will have.',                                     level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-transport-a1',      track:'🟢 A1 · Survival Vocab',    title:'Getting Around — Transport',                 desc:'Bus, train, taxi, plane + go by / take / catch. Pair with a city map for speaking.',                                                                  level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-sport-a2',          track:'🟡 A2 · Everyday Vocab',    title:'Sports & Physical Activity',                 desc:'Play football / go swimming / do yoga. Three verb choices (play/go/do) — a classic error source.',                                                   level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-school-a2',         track:'🟡 A2 · Everyday Vocab',    title:'School Subjects & Education',                desc:'Maths, Science, History, Art + "My favourite subject is…". Extend into a speaking personal reflection.',                                             level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-emotions-a2',       track:'🟡 A2 · Everyday Vocab',    title:'Emotions & Feelings',                        desc:'Happy, sad, excited, bored, nervous, confused. Practise with face cards and "How do you feel when…?".',                                              level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'v-city-a2',           track:'🟡 A2 · Everyday Vocab',    title:'In the City — places & directions',          desc:'Bank, supermarket, library, post office + turn left/right, go straight, take the first left.',                                                      level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'v-cooking-b1',        track:'🔵 B1 · Topical Vocab',     title:'Food & Cooking — verbs & methods',           desc:'Chop, boil, fry, bake, season, blend. Recipe language and describing dishes. Great for project-based speaking.',                                     level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-media-b1',          track:'🔵 B1 · Topical Vocab',     title:'Media & Entertainment',                      desc:'Broadcast, channel, podcast, streaming, celebrity, review. A-list collocations from the entertainment world.',                                         level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-culture-b1',        track:'🔵 B1 · Topical Vocab',     title:'Culture & Traditions',                       desc:'Festival, ceremony, ritual, custom, heritage, generation. Cross-cultural comparisons as discussion starter.',                                          level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'v-nature-b1',         track:'🔵 B1 · Topical Vocab',     title:'Nature & Geography',                         desc:'Mountain, valley, coast, desert, rainforest, wildlife. Descriptive collocations + a short passage about a place.',                                    level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-crime-b2',          track:'🟠 B2 · Topical Vocab',     title:'Crime & Law',                                desc:'Theft, fraud, suspect, verdict, sentence, innocent. Passive structures + a crime-news reading comprehension.',                                        level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'v-politics-b2',       track:'🟠 B2 · Topical Vocab',     title:'Politics & Society',                         desc:'Election, democracy, policy, reform, protest, rights. High-frequency words for reading newspapers and debates.',                                     level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'v-art-b2',            track:'🟠 B2 · Topical Vocab',     title:'Art, Music & Literature',                    desc:'Composer, gallery, genre, playwright, debut, masterpiece. Reviewing and describing cultural works.',                                                  level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-finance-b2',        track:'🟠 B2 · Topical Vocab',     title:'Personal Finance & Money',                   desc:'Budget, invest, mortgage, loan, inflation, salary. Cover tax, savings, and everyday financial decisions.',                                           level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-phrasalAdv-c1',     track:'🔴 C1 · Advanced Vocab',    title:'Phrasal Verbs in Context — Level C1',        desc:'Back down, bring about, call off, phase out, put forward. Sixty C1 phrasal verbs in authentic sentence sets.',                                       level:'C1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-academic-c1',       track:'🔴 C1 · Advanced Vocab',    title:'Academic Vocabulary — AWL Top 50',           desc:'Analyse, concept, evidence, significant, establish, framework. The most useful words from the Academic Word List.',                                   level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-medical-c1',        track:'🔴 C1 · Advanced Vocab',    title:'Medical & Health Vocabulary',                desc:'Diagnosis, symptom, prescription, chronic, prognosis, dose. For students in healthcare or preparing for medical readings.',                            level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-legal-c1',          track:'🔴 C1 · Advanced Vocab',    title:'Legal English — Contracts & Rights',         desc:'Clause, breach, liable, defendant, jurisdiction, statute. Formal legal register for business or law-adjacent learners.',                            level:'C1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-proverbs-c2',       track:'🟣 C2 · Mastery',          title:'Idioms, Proverbs & Fixed Expressions',       desc:'Don\'t beat around the bush, bite the bullet, it goes without saying. Native-speaker expression fluency.',                                           level:'C2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'v-register-c2',       track:'🟣 C2 · Mastery',          title:'Register & Style — formal, neutral, informal', desc:'Commence vs start, assistance vs help, reside vs live. Mastering register shift for translation and tone.',                                        level:'C2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ BUSINESS ENGLISH PACK ═══════════════════════════ */
    { id:'biz-email-b1',        track:'💼 Business English · B1',  title:'Business Emails — structure & tone',         desc:'Subject line, opening, body, closing. Cover request/apology/follow-up types with template mini-tasks.',                                              level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'w2' } },
    { id:'biz-meetings-b2',     track:'💼 Business English · B2',  title:'Running & Participating in Meetings',        desc:'Agenda, action points, AOB, take the floor, circle back. From chairing to contributing — full meeting language.',                                    level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'biz-present-b2',      track:'💼 Business English · B2',  title:'Business Presentations',                     desc:'Today I\'d like to talk about… Moving on to… To summarise… As you can see… Classic signposting for slides and pitches.',                            level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'biz-phone-b1',        track:'💼 Business English · B1',  title:'Professional Phone Calls',                   desc:'Could I speak to…? I\'m calling about… I\'ll put you through. Dealing with difficult calls and voicemail.',                                        level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'biz-negotiate-c1',    track:'💼 Business English · C1',  title:'Negotiation Language',                       desc:'That\'s a fair point, however… We could offer X if you… I\'m afraid that\'s not possible. Advanced negotiation tactics.',                          level:'C1', duration:'55 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'biz-report-b2',       track:'💼 Business English · B2',  title:'Writing Business Reports',                   desc:'Executive summary, methodology, findings, recommendation. Formal structure and appropriate hedging language.',                                       level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'biz-interview-b2',    track:'💼 Business English · B2',  title:'Job Interviews in English',                  desc:'Tell me about yourself. What are your strengths? Where do you see yourself in 5 years? Model answers and coaching.',                                 level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'biz-network-b2',      track:'💼 Business English · B2',  title:'Networking & Small Talk',                    desc:'So what do you do? Have you been to one of these before? Breaking the ice and keeping conversation alive.',                                          level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'biz-collocations-c1', track:'💼 Business English · C1',  title:'Business Collocations & Idioms',             desc:'Hit a target, reach a deadline, run a campaign, cut costs, gain market share. High-density collocation training.',                                   level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'biz-hr-b2',           track:'💼 Business English · B2',  title:'HR & People Management Language',            desc:'Recruitment, onboarding, performance review, redundancy, appraisal. Vocabulary for managers and HR professionals.',                                  level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ IELTS / EXAM PREP PACK ═══════════════════════════ */
    { id:'ielts-task1-line-b2', track:'📝 IELTS · Writing Task 1', title:'Describing Line & Bar Charts',               desc:'The graph shows a significant increase… Peaked at… Fluctuated between. Language for charts with model answer walkthrough.', level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'ielts-task1-pie-b2',  track:'📝 IELTS · Writing Task 1', title:'Describing Pie Charts & Tables',             desc:'The largest proportion… accounted for a third… Comparing and contrasting data groups in a single paragraph.',                level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'ielts-task1-process-c1', track:'📝 IELTS · Writing Task 1', title:'Describing Processes & Diagrams',         desc:'First, the material is fed into… Next it undergoes… Passive-heavy sequential process description writing.',                   level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'ielts-task2-opinion-b2', track:'📝 IELTS · Writing Task 2', title:'Opinion Essay — IELTS Band 7 strategies', desc:'State your position, provide two arguments, refute counter-argument, conclude. Model answer band analysis.',              level:'B2', duration:'55 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'ielts-task2-discuss-c1', track:'📝 IELTS · Writing Task 2', title:'Discussion Essay — balanced arguments',   desc:'While some argue that… others contend… Ultimately… Balance and weigh two sides at C1 with cohesive linkers.',             level:'C1', duration:'55 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'ielts-speak1-b2',     track:'📝 IELTS · Speaking',       title:'Speaking Part 1 — personal questions',       desc:'Talk about yourself fluently for 4–5 minutes. Range, accuracy, fluency, and pronunciation band descriptors.',             level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'ielts-speak2-b2',     track:'📝 IELTS · Speaking',       title:'Speaking Part 2 — 2-minute monologue',       desc:'Cue card structure: Describe a time when… Cover all bullet points and extend naturally to reach 2 full minutes.',       level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'ielts-speak3-c1',     track:'📝 IELTS · Speaking',       title:'Speaking Part 3 — abstract discussion',      desc:'Do you think…? What are the long-term effects…? Expand and justify opinions at an advanced level.',                       level:'C1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'ielts-read-skim-b2',  track:'📝 IELTS · Reading',        title:'Skimming & Scanning strategies',             desc:'Finding main idea vs specific detail under time pressure. Speed-reading drills and T/F/NG technique.',                      level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r2' } },
    { id:'ielts-read-match-c1', track:'📝 IELTS · Reading',        title:'Matching Headings & Paragraph features',     desc:'Paragraph intention vs what it says. Avoid distractor traps in matching tasks — a taught skill.',                         level:'C1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r2' } },
    { id:'ielts-listen-b2',     track:'📝 IELTS · Listening',      title:'IELTS Listening — form completion',          desc:'Name, postcode, booking number. Spelling and number conventions + predicting answer types before the audio.',            level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l2' } },
    { id:'ielts-vocab-b2',      track:'📝 IELTS · Vocabulary',     title:'IELTS Academic Vocabulary — key themes',     desc:'Environment, globalisation, technology, health, education. The five most common IELTS topics with key lexis.',           level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ PRONUNCIATION PACK ═══════════════════════════ */
    { id:'pron-vowels-a1',      track:'🗣 Pronunciation · Basics', title:'English Vowel Sounds — short vs long',       desc:'/ɪ/ vs /iː/ (bit/beat), /ʊ/ vs /uː/ (full/fool). Minimal pairs drilling for early-stage learners.',                      level:'A1', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-th-a2',          track:'🗣 Pronunciation · Basics', title:'/θ/ and /ð/ — think & this',                 desc:'Tongue placement, voiced vs voiceless. Contrasting with /t/, /d/, /s/, /z/ substitutions common in Slavic speakers.',    level:'A2', duration:'25 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-schwa-b1',       track:'🗣 Pronunciation · Core',   title:'Schwa /ə/ — the most common English sound',  desc:'About, banana, teacher, the. Unstressed syllables and why they don\'t match the spelling.',                              level:'B1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-stress-b1',      track:'🗣 Pronunciation · Core',   title:'Word Stress — stress patterns in English',   desc:'PHOtograph, phoTOgraphy, photoGRAPHic. Stress shift in word families and how it changes the vowel sounds.',               level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-connected-b2',   track:'🗣 Pronunciation · Fluency', title:'Connected Speech — linking & reduction',    desc:'Gonna, wanna, d\'you, in a minute → inna minute. The contractions and reductions native speakers actually use.',          level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-intonation-b2',  track:'🗣 Pronunciation · Fluency', title:'Intonation — meaning through tone',         desc:'Falling for statements, rising for questions, fall-rise for uncertainty. How tone changes politeness and meaning.',       level:'B2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },
    { id:'pron-cluster-c1',     track:'🗣 Pronunciation · Advanced', title:'Consonant Clusters — strengths & blends',  desc:'Strengths /strɛŋkθs/. Twelfths. Clusters at word boundaries in fluent speech. Drills + slow/fast audio.',               level:'C1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ TOPIC-BASED LESSON PACK ═══════════════════════════ */
    { id:'top-socialmedia-b1',  track:'🌐 Topics · Modern Life',   title:'Social Media & Digital Life',                desc:'Post, like, share, go viral, scroll, follow, unfollow. Digital etiquette and screen time discussion.',                    level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-travel-a2',       track:'🌐 Topics · Everyday',      title:'At the Airport — check-in to boarding',      desc:'Security check, boarding gate, overhead locker, turbulence. Full airport scenario role-play.',                           level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'top-hotel-a2',        track:'🌐 Topics · Everyday',      title:'At the Hotel — booking & complaints',        desc:'I have a reservation / The shower isn\'t working / Could you bring extra towels? Polite complaint language.',          level:'A2', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'top-doctor-b1',       track:'🌐 Topics · Everyday',      title:'At the Doctor\'s — symptoms & advice',       desc:'I\'ve got a temperature / It started two days ago / Take these twice a day. Healthcare survival language.',             level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s2' } },
    { id:'top-environment-b2',  track:'🌐 Topics · Society',       title:'Climate Change & The Environment',           desc:'Carbon footprint, renewable, fossil fuels, biodiversity, sustainable. Data chart + discussion + essay plan.',           level:'B2', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-ai-b2',           track:'🌐 Topics · Modern Life',   title:'Artificial Intelligence — benefits & risks', desc:'Algorithm, bias, automate, displace, generate. A balanced debate block on the impact of AI on society.',              level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-education-b1',    track:'🌐 Topics · Society',       title:'Education Systems Around the World',         desc:'State school, private school, curriculum, tuition fees, dropout. Cross-cultural comparison and opinion-giving.',        level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-gender-c1',       track:'🌐 Topics · Society',       title:'Gender, Equality & Workplace Issues',        desc:'Gender pay gap, glass ceiling, parental leave, discrimination. Balanced discussion with data and counter-argument.',    level:'C1', duration:'55 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-science-b2',      track:'🌐 Topics · Knowledge',     title:'Science & Technology Breakthroughs',         desc:'Genome, vaccine, space exploration, quantum computing. Describing research findings and speculating about the future.',  level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-history-b1',      track:'🌐 Topics · Knowledge',     title:'Talking About History & Periods',            desc:'The Industrial Revolution, ancient, medieval, modern era. Time expressions and narrative past tenses for history talks.', level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'top-wellbeing-b1',    track:'🌐 Topics · Modern Life',   title:'Mental Health & Wellbeing',                  desc:'Anxiety, burnout, mindfulness, resilience, therapy. Sensitive vocabulary with discussion frameworks.',                  level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'top-money-a2',        track:'🌐 Topics · Everyday',      title:'Talking About Money — basic finance',        desc:'Cost, price, afford, cheap, expensive, save, spend, borrow, lend. A1/A2 money vocabulary in everyday context.',        level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },
    { id:'top-future-b2',       track:'🌐 Topics · Society',       title:'The Future of Work',                         desc:'Remote work, automation, freelancing, gig economy, reskilling. Speculative language + debate.',                       level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s3' } },
    { id:'top-food-culture-b1', track:'🌐 Topics · Culture',       title:'Food Culture — cuisine & customs',           desc:'Street food, culinary tradition, fusion, fasting. Cross-cultural food discussion and recipe-describing language.',     level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'s1' } },
    { id:'top-fashion-a2',      track:'🌐 Topics · Everyday',      title:'Fashion & Personal Style',                   desc:'Casual, formal, trendy, vintage, sustainable fashion. Describing outfits and talking about style preferences.',       level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'vocab', kind:'lesson', action:{ type:'template' } },

    /* ═══════════════════════════ WRITING EXTENDED PACK ═══════════════════════════ */
    { id:'writ-paragraph-b1',   track:'✍️ Writing · Structure',    title:'Paragraph Writing — topic & support',        desc:'Topic sentence, supporting details, example, concluding sentence. The building block of every essay.',                 level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-argreport-b2',   track:'✍️ Writing · Formal',      title:'Argumentative Report',                       desc:'Introduction, two balanced body sections with data, final recommendation. Formal impersonal style throughout.',       level:'B2', duration:'55 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-review-b2',      track:'✍️ Writing · Semi-formal', title:'Writing Reviews — film, book, restaurant',   desc:'Brief summary, positive points, negative points, recommendation. Register-appropriate review language.',              level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-letter-b1',      track:'✍️ Writing · Formal',      title:'Formal Letter of Complaint',                 desc:'I am writing to complain about… I would be grateful if… I look forward to hearing from you. Full complaint letter.',   level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-story-b1',       track:'✍️ Writing · Creative',    title:'Short Story — narrative techniques',          desc:'Hook, rising action, climax, resolution. Sequencing words and narrative tense blend. 150-word writing sprint.',       level:'B1', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-academic-c1',    track:'✍️ Writing · Academic',    title:'Academic Essay — thesis & argument',          desc:'Thesis statement, argumentation, counterargument, hedging language. C1 essay cohesion markers and tone.',            level:'C1', duration:'60 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'w1' } },
    { id:'writ-summary-b2',     track:'✍️ Writing · Academic',    title:'Summary Writing — paraphrase & condense',    desc:'Identify key points, paraphrase without copying, reduce by 50%. Core skills for academic and exam writing.',         level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r3' } },

    /* ═══════════════════════════ READING EXTENDED PACK ═══════════════════════════ */
    { id:'read-predict-a2',     track:'📖 Reading · Strategies',   title:'Prediction & Pre-reading Skills',            desc:'Using titles, images, and keywords to predict content before reading. Boosts engagement and comprehension speed.',     level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'read-inference-b2',   track:'📖 Reading · Strategies',   title:'Reading Between the Lines — inference',      desc:'What does the author imply? Why did the character do X? Teach explicit vs implicit meaning in text.',                 level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r3' } },
    { id:'read-vocab-b1',       track:'📖 Reading · Strategies',   title:'Guessing Vocabulary from Context',           desc:'Surrounding clues, part of speech, prefix/suffix. Beat the unknown word without stopping to look it up.',            level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'v4' } },
    { id:'read-graded-a1',      track:'📖 Reading · Texts',        title:'Graded Reader — A1 Short Story',             desc:'Simple narrative with controlled vocabulary. Focus on characters, setting, and sequence. Perfect for A1 classes.',     level:'A1', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r1' } },
    { id:'read-magazine-b1',    track:'📖 Reading · Texts',        title:'Magazine Article — lifestyle topic',          desc:'Feature article with headings, quotes, and statistics. Skim for gist, scan for data, respond to comprehension Q.',  level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r2' } },
    { id:'read-opinion-b2',     track:'📖 Reading · Texts',        title:'Opinion Column — bias & argument analysis',  desc:'Identify author position, supporting evidence, and rhetorical devices. Prepares for IELTS and Cambridge exams.',      level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'r3' } },

    /* ═══════════════════════════ LISTENING EXTENDED PACK ═══════════════════════════ */
    { id:'list-gist-a2',        track:'🎧 Listening · Strategies', title:'Listening for Gist — main idea first',       desc:'What is the conversation about? What is the speaker\'s attitude? Holistic comprehension before detail.',             level:'A2', duration:'30 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l1' } },
    { id:'list-detail-b1',      track:'🎧 Listening · Strategies', title:'Listening for Specific Information',          desc:'Dates, names, numbers, instructions. Training focused listening and note-taking under time pressure.',                level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l1' } },
    { id:'list-accents-b2',     track:'🎧 Listening · Exposure',   title:'Varieties of English — accents & dialects',  desc:'British RP, American General, Australian, Indian English. Exposure + discussion of accents in global communication.',  level:'B2', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l2' } },
    { id:'list-lecture-c1',     track:'🎧 Listening · Academic',   title:'Lecture Listening & Note-taking',             desc:'Headings, signal phrases (firstly, in contrast, to conclude), abbreviations. Academic lecture comprehension skills.',   level:'C1', duration:'50 min', progress:0, langs:['ru','ua','pl'], category:'speaking', kind:'lesson', action:{ type:'tool', target:'l1' } },

    /* ═══════════════════════════ MISTAKES — EXTENDED ═══════════════════════════ */
    { id:'m-confwords-b1',      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',  title:'Confusing Word Pairs',                        desc:'Lend vs borrow, say vs tell, make vs do, learn vs teach. The pairs that every intermediate Slavic student gets wrong.',  level:'B1', duration:'35 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-prepositions-b1',   track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',  title:'Preposition Errors — at / in / on / for / by', desc:'Arrived in London vs arrived at Heathrow. Pay by card. Wait for. Each preposition with its binding rules.',           level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-capitalization-a1', track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',  title:'Capitalisation — English vs Slavic rules',     desc:'Monday (capital), English (capital), but not teacher or winter. Where English capitalises and Slavic languages don\'t.', level:'A1', duration:'20 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'template' } },
    { id:'m-tense-b1',          track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',  title:'Tense Sequence Errors — did vs have done',     desc:'I saw him yesterday vs I have just seen him. The most persistent confusion for Slavic learners at B1.',                level:'B1', duration:'40 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } },
    { id:'m-translate-b2',      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',  title:'Direct Translation Traps',                    desc:'Думати → think about (not think for). Залежати → depend on (not from). Forty common calques to fix.',                level:'B2', duration:'45 min', progress:0, langs:['ru','ua','pl'], category:'mistakes', kind:'lesson', action:{ type:'tool', target:'g3' } }
  ]
};
