window.TEACHEDOS_DATA = {
  tools: [
    { id:'r1', name:'Create a Text on Any Topic with Your Vocabulary', desc:'Paste a topic and a word list to generate a CEFR-friendly text. Great for reading work, homework, or a custom lead-in after a vocabulary lesson.', tags:['Reading','Vocabulary'], badge:null, icon:'📄', group:'reading' },
    { id:'r2', name:'Create ABCD Questions', desc:'Локальний модуль створює multiple-choice запитання з тексту прямо на GitHub Pages без API-ключа. Зручно для швидких reading quizzes.', tags:['Reading'], badge:'New', icon:'🔡', group:'reading' },
    { id:'r3', name:'Create Open Questions', desc:'Produces open-ended comprehension questions that encourage critical thinking and discussion around the text.', tags:['Reading'], badge:null, icon:'❓', group:'reading' },
    { id:'r4', name:'Create True/False Statements', desc:'Creates a true/false reading exercise to quickly check if students understood the key facts and details of the text.', tags:['Reading'], badge:'Pro', icon:'✅', group:'reading' },
    { id:'w1', name:'Writing Prompts', desc:'Generates creative or structured writing prompts tailored to a specific topic and CEFR level — great for in-class or homework writing tasks.', tags:['Writing'], badge:null, icon:'✍️', group:'writing' },
    { id:'w2', name:'Dialogue Creator', desc:'Creates a realistic dialogue between two characters on any topic and level. Use for reading, comprehension, or role-play speaking practice.', tags:['Writing','Speaking'], badge:null, icon:'💬', group:'writing' },
    { id:'l1', name:'Audio & Video Question Creator', desc:'Upload any audio or video file and auto-generate open questions, multiple-choice questions, or true/false statements based on the content.', tags:['Listening'], badge:'Pro', icon:'🎙️', group:'listening' },
    { id:'l2', name:'Convert Audio & Video to Text', desc:'Transcribes mp3, mp4, or YouTube links into a readable transcript ready for classroom use as a reading or gap-fill activity.', tags:['Listening'], badge:'Pro', icon:'🎬', group:'listening' },
    { id:'s1', name:'Find Discussion Questions', desc:'Creates engaging discussion questions on any topic — use as a warm-up, while-lesson discussion, or speaking fluency practice for any level.', tags:['Speaking'], badge:null, icon:'🗣️', group:'speaking' },
    { id:'s2', name:'Role-Play Scenarios', desc:'Generates role-play cards and scenario prompts for pair or group speaking activities. Set the context, and get ready-to-use speaking tasks.', tags:['Speaking'], badge:null, icon:'🎭', group:'speaking' },
    { id:'s3', name:'Four Opinions Generator', desc:'Генерує 4 різні англомовні позиції за темою, рівнем і довжиною. Добре працює як speaking warm-up або debate starter.', tags:['Speaking'], badge:'New', icon:'🧠', group:'speaking' },
    { id:'v1', name:'Word-Image Matching', desc:'Creates a vocabulary exercise where students match each word to the correct picture. Boosts visual recognition and word retention.', tags:['Vocabulary'], badge:'New', icon:'🖼️', group:'vocabulary' },
    { id:'v2', name:'Word-Definition Matching', desc:'Інтерактивна гра на співставлення слова з визначенням. Перекладено українською та вбудовано прямо в TeachedOS.', tags:['Vocabulary'], badge:'New', icon:'🔍', group:'vocabulary' },
    { id:'v3', name:'Create a List of Sentences with Your Vocabulary', desc:'Generates example sentences using your target vocabulary list. Great before a Fill-in-the-Gap task or as a quick context bank for a new word set.', tags:['Vocabulary'], badge:'Pro', icon:'📋', group:'vocabulary' },
    { id:'v4', name:'Fill in the Gap', desc:'Replaces chosen words in a text with blank gaps and provides the word list separately. Works for vocabulary recall and grammar tense practice.', tags:['Vocabulary','Grammar'], badge:null, icon:'✏️', group:'vocabulary' },
    { id:'g1', name:'Fill in the Gap', desc:'Replaces chosen words in a text with gaps. Add verb forms or tense markers to turn it into a grammar tense or form exercise.', tags:['Grammar','Vocabulary'], badge:null, icon:'✏️', group:'grammar' },
    { id:'g2', name:'Grammar Worksheets', desc:'Generates structured grammar worksheets with clear explanations, examples, and progressive exercises for any grammar point and CEFR level.', tags:['Grammar'], badge:null, icon:'📑', group:'grammar' },
    { id:'g3', name:'Error Correction', desc:'Creates sentences with intentional grammar or vocabulary mistakes for students to identify and fix. Great for proofreading and accuracy tasks.', tags:['Grammar'], badge:'Pro', icon:'🔧', group:'grammar' },
    { id:'u1', name:'CEFR Level Checker', desc:'Paste any text and instantly determine its CEFR proficiency level (A1–C2) according to the Common European Framework of Reference.', tags:['Utility'], badge:'Pro', icon:'📊', group:'utility' },
    { id:'u2', name:'Lesson Plan Generator', desc:'Input a topic, level, and lesson duration — get a complete, structured lesson plan with objectives, activities, and timing suggestions.', tags:['Utility'], badge:null, icon:'📅', group:'utility' }
  ],
  games: [
    {
      id:'quiz-lab',
      toolId:'r2',
      icon:'🔡',
      accent:'linear-gradient(145deg,#7ca8ff,#356dff)',
      title:'LinguaQuiz AI',
      eyebrow:'§ reading generator',
      subtitle:'ABCD Questions · Local Mode',
      desc:'Локальний модуль для reading practice: вставляєте текст і отримуєте multiple-choice питання прямо у вікні OS без API-ключів і зовнішнього бекенду.',
      skill:'Reading',
      mode:'Offline',
      audience:'A1–C2',
      embedUrl:'games/linguaquiz-ai-uk.html?embed=1',
      rawUrl:'games/linguaquiz-ai-uk.html'
    },
    {
      id:'opinions-lab',
      toolId:'s3',
      icon:'🧠',
      accent:'linear-gradient(145deg,#b687ff,#7f56e3)',
      title:'Four Opinions Generator',
      eyebrow:'§ speaking starter',
      subtitle:'Debate Module · Four Voices',
      desc:'Органічний speaking-модуль для warm-up, pair work та discussion circles. Створює чотири контрастні точки зору англійською в компактному системному режимі.',
      skill:'Speaking',
      mode:'Offline',
      audience:'A1–C1',
      embedUrl:'games/four-opinions-uk.html?embed=1',
      rawUrl:'games/four-opinions-uk.html'
    },
    {
      id:'match-lab',
      toolId:'v2',
      icon:'🔍',
      accent:'linear-gradient(145deg,#ff9a62,#d96b2b)',
      title:'Word-Definition Matching',
      eyebrow:'§ vocabulary module',
      subtitle:'Matching Grid · Embedded',
      desc:'Інтерактивна вправа на співставлення слів і визначень. Перекладена українською і підготовлена як повноцінний модуль TeachedOS, а не окрема сторінка.',
      skill:'Vocabulary',
      mode:'Playable',
      audience:'A2–B2',
      embedUrl:'games/word-definition-match.html?embed=1',
      rawUrl:'games/word-definition-match.html'
    },
    {
      id:'text-builder-lab',
      toolId:'r1',
      icon:'📄',
      accent:'linear-gradient(145deg,#7ca8ff,#4567f4)',
      title:'Text Builder',
      eyebrow:'§ reading generator',
      subtitle:'Topic + Vocabulary · Local Mode',
      desc:'Генерує короткий текст на тему з вашою лексикою і рівнем CEFR. Це наш локальний аналог одного з базових Twee reading modules.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C1',
      embedUrl:'games/twee-module-studio.html?module=text-vocab&embed=1',
      rawUrl:'games/twee-module-studio.html?module=text-vocab'
    },
    {
      id:'open-questions-lab',
      toolId:'r3',
      icon:'❓',
      accent:'linear-gradient(145deg,#84b8ff,#4d91ff)',
      title:'Open Questions',
      eyebrow:'§ reading check',
      subtitle:'Comprehension Questions · Local Mode',
      desc:'Створює відкриті питання до тексту у стилі Twee workflow: швидко, локально і без зовнішніх сервісів.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=open-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=open-questions'
    },
    {
      id:'true-false-lab',
      toolId:'r4',
      icon:'✅',
      accent:'linear-gradient(145deg,#6ed39c,#4fb58b)',
      title:'True / False',
      eyebrow:'§ reading exercise',
      subtitle:'Statement Builder · Local Mode',
      desc:'Генерує true/false вправу на основі тексту. Підходить для короткої comprehension check activity після reading.',
      skill:'Reading',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=true-false&embed=1',
      rawUrl:'games/twee-module-studio.html?module=true-false'
    },
    {
      id:'discussion-lab',
      toolId:'s1',
      icon:'🗣️',
      accent:'linear-gradient(145deg,#bb8cff,#8f61f1)',
      title:'Discussion Questions',
      eyebrow:'§ speaking warm-up',
      subtitle:'Topic Prompts · Local Mode',
      desc:'Підбирає discussion questions на тему для warm-up, pair work або freer speaking. Органічно закриває один із core Twee speaking use cases.',
      skill:'Speaking',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=discussion-questions&embed=1',
      rawUrl:'games/twee-module-studio.html?module=discussion-questions'
    },
    {
      id:'sentence-list-lab',
      toolId:'v3',
      icon:'📋',
      accent:'linear-gradient(145deg,#ffaf73,#f08d54)',
      title:'Sentence List',
      eyebrow:'§ vocabulary builder',
      subtitle:'Target Vocabulary · Local Mode',
      desc:'Створює список прикладових речень з вашою лексикою, щоб швидко будувати контекст, drills і подальші gap-fill вправи.',
      skill:'Vocabulary',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=sentence-list&embed=1',
      rawUrl:'games/twee-module-studio.html?module=sentence-list'
    },
    {
      id:'gap-lab',
      toolIds:['v4','g1'],
      icon:'✏️',
      accent:'linear-gradient(145deg,#ef8d9a,#dc6a79)',
      title:'Fill in the Gap',
      eyebrow:'§ grammar + vocabulary',
      subtitle:'Gap Exercise · Local Mode',
      desc:'Будує gap-fill вправу з тексту і word bank. Працює і як vocabulary recall, і як grammar/tense adaptation inside TeachedOS.',
      skill:'Grammar',
      mode:'Generate',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=fill-gap&embed=1',
      rawUrl:'games/twee-module-studio.html?module=fill-gap'
    },
    {
      id:'cefr-lab',
      toolId:'u1',
      icon:'📊',
      accent:'linear-gradient(145deg,#a9b5c4,#7f8a98)',
      title:'CEFR Checker',
      eyebrow:'§ utility module',
      subtitle:'Rough Level Estimate · Local Mode',
      desc:'Дає швидку локальну CEFR-оцінку тексту і показує, чому модуль схиляється до певного рівня.',
      skill:'Utility',
      mode:'Analyze',
      audience:'A1–C2',
      embedUrl:'games/twee-module-studio.html?module=cefr-checker&embed=1',
      rawUrl:'games/twee-module-studio.html?module=cefr-checker'
    }
  ],
  curriculum: [
    {
      id:'curr-articles',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Articles: a, an, the',
      desc:'The biggest challenge for Slavic speakers — English has three articles where Russian, Ukrainian and Polish have none. Master when to use each one.',
      level:'A2',
      duration:'30 min',
      progress:72,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:1 }
    },
    {
      id:'curr-tenses',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'English Tenses vs. Slavic Aspect',
      desc:'Why English has 12 tenses but Slavic languages use aspect. Map your intuition to the English tense system and compare completed vs ongoing action.',
      level:'B1',
      duration:'45 min',
      progress:48,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'note', noteId:3 }
    },
    {
      id:'curr-phrasal',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'Phrasal Verbs: get, make, take, do',
      desc:'The four most essential phrasal verb families in everyday English. Learn them in context and turn them into a review note set.',
      level:'B1',
      duration:'35 min',
      progress:90,
      langs:['ru','ua','pl'],
      category:'vocab',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-prepositions',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Grammar',
      title:'Prepositions: at / in / on',
      desc:'English prepositions do not map cleanly to Slavic patterns. Build a short classroom summary and example bank for place and time use.',
      level:'A2',
      duration:'25 min',
      progress:100,
      langs:['ru','ua','pl'],
      category:'grammar',
      kind:'lesson',
      action:{ type:'template' }
    },
    {
      id:'curr-order',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Mistakes',
      title:'Word Order: No Flexibility',
      desc:'In English, sentence structure is fixed. Use this section to build a quick remediation note with good and bad examples.',
      level:'A2',
      duration:'20 min',
      progress:35,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'tool', target:'g3' }
    },
    {
      id:'curr-false-friends',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Vocabulary',
      title:'False Friends: RU/UA/PL → EN',
      desc:'«Магазин» is not a magazine. «Фабрика» is not a fabric. The most dangerous false cognates for Slavic speakers.',
      level:'B1',
      duration:'30 min',
      progress:0,
      langs:['ru','ua','pl'],
      category:'mistakes',
      kind:'lesson',
      action:{ type:'note', noteId:2 }
    },
    {
      id:'curr-speaking-prompts',
      track:'🇷🇺🇺🇦🇵🇱 → 🇬🇧 Speaking',
      title:'Discussion Starters for Class',
      desc:'Generate warm-up prompts, discussion loops, and short pair-work questions to move from passive vocabulary into active speaking.',
      level:'A2–B2',
      duration:'15 min',
      progress:15,
      langs:['ru','ua','pl'],
      category:'speaking',
      kind:'lesson',
      action:{ type:'tool', target:'s1' }
    },
    {
      id:'curr-game-match',
      track:'🎮 Interactive Lab · Vocabulary',
      title:'Word-Definition Matching',
      desc:'Interactive matching grid for vocabulary review. Great as a warm-up, station activity, or quick recap inside the OS window system.',
      level:'A2',
      duration:'Game',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'match-lab' }
    },
    {
      id:'curr-game-quiz',
      track:'🎮 Interactive Lab · Reading',
      title:'ABCD Questions from Text',
      desc:'Paste a text and generate a lightweight reading quiz inside the app. Useful for instant comprehension checks in class.',
      level:'A2–C2',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'quiz-lab' }
    },
    {
      id:'curr-game-opinions',
      track:'🎮 Interactive Lab · Speaking',
      title:'Four Opinions Generator',
      desc:'Launch the speaking module and get four contrasting opinions for pair work, debate practice, or discussion circles.',
      level:'A1–C1',
      duration:'Tool',
      progress:0,
      langs:['ru','ua','pl'],
      category:'games',
      kind:'game',
      action:{ type:'game', target:'opinions-lab' }
    }
  ]
};
