/* ═══════════════════════════════════════════════════════════════════════
   TeachEd — Vocabulary Library
   20 thematic dictionaries × 5 CEFR levels × ~25–30 words each
   ≈ 550 entries total. Each word: [en, uk, ru, example_en]

   Consumers:
     • game-builder.html  → "Load from topic" picker
     • quiz-builder.html  → "Generate from topic" templates
     • games/*.html       → ?topic=<id>&level=<A1..C1> URL params
     • community.html     → ready-made game variants by topic
   ═══════════════════════════════════════════════════════════════════════ */

(function () {
  // Compact entry format keeps file size sane while preserving readability.
  // Tuple: [english, ukrainian, russian, example_sentence]

  const TOPICS = {
    // ════════ 1. TRAVEL & TOURISM ════════
    travel: {
      name: 'Travel & Tourism',
      icon: '✈️',
      color: '#8FE6E6',
      A1: [
        ['airport',     'аеропорт',      'аэропорт',       'I am at the airport.'],
        ['ticket',      'квиток',        'билет',          'Where is my ticket?'],
        ['hotel',       'готель',        'отель',          'The hotel is near the beach.'],
        ['passport',    'паспорт',       'паспорт',        'Show me your passport, please.'],
        ['suitcase',    'валіза',        'чемодан',        'My suitcase is heavy.'],
        ['map',         'карта',         'карта',          'I need a map of the city.'],
        ['bus',         'автобус',       'автобус',        'The bus is late.'],
        ['taxi',        'таксі',         'такси',          'Let’s take a taxi.'],
      ],
      A2: [
        ['departure',   'відправлення',  'отправление',    'Our departure is at 7 AM.'],
        ['arrival',     'прибуття',      'прибытие',       'Check the arrival board.'],
        ['luggage',     'багаж',         'багаж',          'Where do I collect my luggage?'],
        ['booking',     'бронювання',    'бронирование',   'I made a booking online.'],
        ['journey',     'подорож',       'путешествие',    'It was a long journey.'],
        ['guide',       'гід',           'гид',            'Our guide spoke three languages.'],
        ['border',      'кордон',        'граница',        'We crossed the border at noon.'],
        ['delay',       'затримка',      'задержка',       'There was a two-hour delay.'],
      ],
      B1: [
        ['itinerary',   'маршрут',       'маршрут',        'Send me your itinerary.'],
        ['destination', 'місце призначення','место назначения','What’s your final destination?'],
        ['accommodation','проживання',   'проживание',     'Accommodation is included.'],
        ['voyage',      'плавання',      'плавание',       'A sea voyage takes patience.'],
        ['customs',     'митниця',       'таможня',        'Customs took twenty minutes.'],
        ['boarding',    'посадка',       'посадка',        'Boarding starts in five minutes.'],
        ['cancellation','скасування',    'отмена',         'Cancellation fees are non-refundable.'],
      ],
      B2: [
        ['layover',     'пересадка',     'пересадка',      'I have a six-hour layover in Vienna.'],
        ['detour',      'об’їзд',        'объезд',         'We took a detour through the forest.'],
        ['turbulence',  'турбулентність','турбулентность', 'Mild turbulence is normal.'],
        ['embassy',     'посольство',    'посольство',     'Call the embassy if you lose your passport.'],
        ['visa waiver', 'безвізовий режим','безвизовый режим','The visa waiver covers 90 days.'],
        ['jet lag',     'джетлаґ',       'джетлаг',        'Jet lag hits me hardest on day two.'],
      ],
      C1: [
        ['off-the-beaten-path','неходжений','малоизвестный','We love off-the-beaten-path villages.'],
        ['cosmopolitan','космополітичний','космополитичный','Berlin feels deeply cosmopolitan.'],
        ['indigenous',  'корінний',      'коренной',       'We met indigenous artisans in the highlands.'],
        ['expatriate',  'емігрант',      'экспат',         'A community of expatriates gathers each Sunday.'],
        ['wanderlust',  'жага подорожей','охота странствовать','Her wanderlust never fades.'],
      ],
    },

    // ════════ 2. FOOD & DRINKS ════════
    food: {
      name: 'Food & Drinks',
      icon: '🍕',
      color: '#FFB5AE',
      A1: [
        ['bread',       'хліб',          'хлеб',           'I eat bread for breakfast.'],
        ['water',       'вода',          'вода',           'Can I have water, please?'],
        ['apple',       'яблуко',        'яблоко',         'An apple a day keeps the doctor away.'],
        ['milk',        'молоко',        'молоко',         'I drink milk every morning.'],
        ['rice',        'рис',           'рис',            'Rice is a common side dish.'],
        ['cheese',      'сир',           'сыр',            'I love French cheese.'],
        ['egg',         'яйце',          'яйцо',           'One egg, fried, please.'],
        ['tea',         'чай',           'чай',            'Black tea with lemon.'],
      ],
      A2: [
        ['breakfast',   'сніданок',      'завтрак',        'What did you have for breakfast?'],
        ['vegetable',   'овоч',          'овощ',           'Eat more vegetables.'],
        ['dessert',     'десерт',        'десерт',         'I’ll skip dessert tonight.'],
        ['snack',       'перекус',       'перекус',        'I need a quick snack.'],
        ['recipe',      'рецепт',        'рецепт',         'Send me the recipe.'],
        ['flavour',     'смак',          'вкус',           'This soup has a rich flavour.'],
        ['spicy',       'гострий',       'острый',         'I don’t like spicy food.'],
        ['fresh',       'свіжий',        'свежий',         'Fresh bread smells amazing.'],
      ],
      B1: [
        ['ingredient',  'інгредієнт',    'ингредиент',     'List the main ingredients.'],
        ['leftovers',   'залишки',       'остатки',        'I’ll eat the leftovers for lunch.'],
        ['portion',     'порція',        'порция',         'A small portion is enough.'],
        ['cuisine',     'кухня',         'кухня',          'Italian cuisine is my favourite.'],
        ['marinate',    'маринувати',    'мариновать',     'Marinate the chicken overnight.'],
        ['garnish',     'гарнір/прикраса','гарнир/украшение','Garnish with fresh parsley.'],
        ['vegetarian',  'вегетаріанський','вегетарианский','We have vegetarian options.'],
      ],
      B2: [
        ['savoury',     'пікантний',     'пикантный',      'I prefer savoury over sweet.'],
        ['mouthwatering','апетитний',    'аппетитный',     'The cake looked mouthwatering.'],
        ['simmer',      'тушкувати на повільному вогні','томить','Simmer for twenty minutes.'],
        ['palate',      'смак/піднебіння','вкус/нёбо',     'She has a refined palate.'],
        ['hearty',      'ситний',        'сытный',         'A hearty stew on a cold night.'],
        ['malnutrition','недоїдання',    'недоедание',     'Malnutrition affects millions.'],
      ],
      C1: [
        ['gastronomy',  'гастрономія',   'гастрономия',    'Lyon is the capital of French gastronomy.'],
        ['umami',       'умамі',         'умами',          'Soy sauce delivers a deep umami flavour.'],
        ['connoisseur', 'знавець',       'знаток',         'A wine connoisseur judged the tasting.'],
        ['epicurean',   'епікурейський', 'эпикурейский',   'An epicurean lifestyle prioritises pleasure.'],
        ['decadent',    'розкішний',     'роскошный',      'A decadent chocolate dessert.'],
      ],
    },

    // ════════ 3. FAMILY & RELATIONSHIPS ════════
    family: {
      name: 'Family & Relationships',
      icon: '👨‍👩‍👧',
      color: '#D8C5FB',
      A1: [
        ['mother',      'мати',          'мать',           'My mother is a teacher.'],
        ['father',      'батько',        'отец',           'My father works at home.'],
        ['sister',      'сестра',        'сестра',         'I have one sister.'],
        ['brother',     'брат',          'брат',           'My brother is older.'],
        ['friend',      'друг',          'друг',           'She is my best friend.'],
        ['baby',        'малюк',         'малыш',          'The baby is sleeping.'],
        ['son',         'син',           'сын',            'They have a son.'],
        ['daughter',    'донька',        'дочь',           'Their daughter is at school.'],
      ],
      A2: [
        ['cousin',      'двоюрідний брат/сестра','двоюродный брат/сестра','My cousin lives in Lviv.'],
        ['neighbour',   'сусід',         'сосед',          'Our neighbour is very friendly.'],
        ['relative',    'родич',         'родственник',    'Most of my relatives live abroad.'],
        ['couple',      'пара',          'пара',           'A young couple just moved in.'],
        ['twins',       'близнюки',      'близнецы',       'They are identical twins.'],
        ['stepmother',  'мачуха',        'мачеха',         'Her stepmother is very kind.'],
        ['grandparents','бабуся й дідусь','бабушка и дедушка','My grandparents live in the village.'],
        ['classmate',   'однокласник',   'одноклассник',   'My old classmate called me.'],
      ],
      B1: [
        ['relationship','стосунки',      'отношения',      'They have a healthy relationship.'],
        ['engaged',     'заручені',      'обручены',       'They got engaged last summer.'],
        ['in-laws',     'свекри/тесть і теща','родители супруга','We are visiting my in-laws.'],
        ['acquaintance','знайомий',      'знакомый',       'He is just an acquaintance.'],
        ['mentor',      'наставник',     'наставник',      'She became my mentor at work.'],
        ['rival',       'суперник',      'соперник',       'They were rivals at school.'],
        ['ancestor',    'предок',        'предок',         'My ancestors came from Galicia.'],
      ],
      B2: [
        ['sibling',     'брат або сестра','брат или сестра','I have three siblings.'],
        ['estranged',   'відчужений',    'отчуждённый',    'They are estranged from their father.'],
        ['nurture',     'виховувати',    'воспитывать',    'Parents nurture their children.'],
        ['confide in',  'звіритися',     'довериться',     'I confide in my older sister.'],
        ['heartbroken', 'із розбитим серцем','с разбитым сердцем','She was heartbroken for months.'],
        ['kinship',     'спорідненість', 'родство',        'They feel a deep kinship.'],
      ],
      C1: [
        ['matriarch',   'матріарх',      'матриарх',       'She is the matriarch of the family.'],
        ['progeny',     'нащадки',       'потомство',      'His progeny inherited the estate.'],
        ['nepotism',    'кумівство',     'кумовство',      'Nepotism plagues the institution.'],
        ['estrangement','відчуження',    'отчуждение',     'The estrangement lasted decades.'],
        ['kindred spirit','споріднена душа','родственная душа','I met a kindred spirit at the workshop.'],
      ],
    },

    // ════════ 4. DAILY ROUTINE ════════
    routine: {
      name: 'Daily Routine',
      icon: '🌅',
      color: '#FFC94A',
      A1: [
        ['wake up',     'прокидатися',   'просыпаться',    'I wake up at 7.'],
        ['breakfast',   'сніданок',      'завтрак',        'I have breakfast at 8.'],
        ['work',        'працювати',     'работать',       'I work in an office.'],
        ['lunch',       'обід',          'обед',           'I eat lunch at noon.'],
        ['home',        'дім',           'дом',            'I go home at 6.'],
        ['dinner',      'вечеря',        'ужин',           'Dinner is at 7.'],
        ['sleep',       'спати',         'спать',          'I sleep eight hours.'],
        ['shower',      'душ',           'душ',            'I take a shower in the morning.'],
      ],
      A2: [
        ['brush teeth', 'чистити зуби',  'чистить зубы',   'I brush my teeth twice a day.'],
        ['get dressed', 'одягатися',     'одеваться',      'I get dressed quickly.'],
        ['commute',     'добиратися на роботу','добираться','My commute is 30 minutes.'],
        ['routine',     'рутина',        'рутина',         'My routine never changes.'],
        ['errand',      'дрібна справа', 'мелкое дело',    'I have a few errands to run.'],
        ['nap',         'короткий сон',  'короткий сон',   'I take a nap after lunch.'],
        ['weekend',     'вихідні',       'выходные',       'I relax on the weekend.'],
        ['housework',   'хатня робота',  'домашняя работа','I do housework on Saturdays.'],
      ],
      B1: [
        ['oversleep',   'проспати',      'проспать',       'Sorry I’m late, I overslept.'],
        ['stick to a schedule','дотримуватися графіка','придерживаться графика','I try to stick to a schedule.'],
        ['unwind',      'розслаблятися', 'расслабляться',  'I unwind by reading.'],
        ['procrastinate','зволікати',    'откладывать',    'I tend to procrastinate.'],
        ['multitask',   'працювати в кількох справах','делать несколько дел','I multitask all day.'],
        ['productive',  'продуктивний',  'продуктивный',   'It was a productive morning.'],
        ['exhausted',   'виснажений',    'измотанный',     'I was exhausted by Friday.'],
      ],
      B2: [
        ['hectic',      'гарячковий',    'суматошный',     'Mondays are always hectic.'],
        ['mundane',     'буденний',      'будничный',      'I find mundane tasks calming.'],
        ['nine-to-five','з дев’ятої до п’ятої','с девяти до пяти','I gave up the nine-to-five.'],
        ['sluggish',    'млявий',        'вялый',          'I feel sluggish without coffee.'],
        ['discipline',  'дисципліна',    'дисциплина',     'Discipline beats motivation.'],
        ['ritual',      'ритуал',        'ритуал',         'My morning ritual is sacred.'],
      ],
      C1: [
        ['monotony',    'монотонність',  'монотонность',   'I broke the monotony with a hike.'],
        ['regimen',     'режим',         'режим',          'A strict regimen helps athletes.'],
        ['rejuvenate',  'відновлювати сили','омолаживать', 'A short trip rejuvenated me.'],
        ['workaholic',  'трудоголік',    'трудоголик',     'He’s a workaholic, never rests.'],
        ['idle',        'неробити',      'бездельничать',  'Don’t idle the afternoon away.'],
      ],
    },

    // ════════ 5. WORK & OFFICE ════════
    work: {
      name: 'Work & Office',
      icon: '💼',
      color: '#D8C5FB',
      A1: [
        ['job',         'робота',        'работа',         'I love my job.'],
        ['boss',        'начальник',     'начальник',      'My boss is kind.'],
        ['office',      'офіс',          'офис',           'The office is downtown.'],
        ['computer',    'комп’ютер',     'компьютер',      'My computer is slow.'],
        ['email',       'імейл',         'имейл',          'I sent you an email.'],
        ['meeting',     'зустріч',       'встреча',        'We have a meeting at 10.'],
        ['team',        'команда',       'команда',        'My team is great.'],
        ['salary',      'зарплата',      'зарплата',       'My salary is good.'],
      ],
      A2: [
        ['colleague',   'колега',        'коллега',        'My colleague helped me.'],
        ['deadline',    'крайній термін','дедлайн',        'The deadline is Friday.'],
        ['project',     'проєкт',        'проект',         'I work on three projects.'],
        ['promotion',   'підвищення',    'повышение',      'I got a promotion last year.'],
        ['interview',   'співбесіда',    'собеседование',  'I have an interview tomorrow.'],
        ['report',      'звіт',          'отчёт',          'Send me the report by 5.'],
        ['contract',    'контракт',      'контракт',       'Sign the contract before Monday.'],
        ['client',      'клієнт',        'клиент',         'Our biggest client is German.'],
      ],
      B1: [
        ['negotiate',   'вести переговори','вести переговоры','We negotiate every clause.'],
        ['workload',    'навантаження',  'нагрузка',       'My workload has doubled.'],
        ['freelance',   'фрилансити',    'фрилансить',     'I freelance on weekends.'],
        ['overtime',    'понаднормово',  'сверхурочно',    'I worked overtime all week.'],
        ['benefits',    'соцпакет',      'соцпакет',       'Great benefits package.'],
        ['supervisor',  'керівник',      'руководитель',   'My supervisor approved the leave.'],
        ['outsource',   'передавати на аутсорс','отдавать на аутсорс','We outsource design to Kyiv.'],
      ],
      B2: [
        ['streamline',  'оптимізувати',  'оптимизировать', 'We streamlined the onboarding process.'],
        ['delegate',    'делегувати',    'делегировать',   'A good manager delegates well.'],
        ['burnout',     'вигорання',     'выгорание',      'Burnout hit me last summer.'],
        ['feedback',    'зворотний зв’язок','обратная связь','I appreciate honest feedback.'],
        ['stakeholder', 'зацікавлена сторона','заинтересованная сторона','Brief the stakeholders first.'],
        ['mentor',      'наставник',     'наставник',      'My mentor changed my career.'],
      ],
      C1: [
        ['micromanage', 'мікроменеджмент','микроменеджмент','Don’t micromanage your team.'],
        ['headhunter',  'хедхантер',     'хедхантер',      'A headhunter reached out on LinkedIn.'],
        ['onboarding',  'адаптація',     'онбординг',      'Our onboarding takes two weeks.'],
        ['restructure', 'реструктуризація','реструктуризация','The company will restructure in Q3.'],
        ['attrition',   'плинність кадрів','текучесть кадров','Attrition is at an all-time low.'],
      ],
    },

    // ════════ 6. SCHOOL & EDUCATION ════════
    education: {
      name: 'School & Education',
      icon: '🎓',
      color: '#CDF24F',
      A1: [
        ['school',      'школа',         'школа',          'I go to school by bus.'],
        ['book',        'книга',         'книга',          'I read books every day.'],
        ['teacher',     'вчитель',       'учитель',        'My teacher is funny.'],
        ['student',     'учень',         'ученик',         'I am a good student.'],
        ['pen',         'ручка',         'ручка',          'I lost my pen.'],
        ['lesson',      'урок',          'урок',           'The English lesson is at 9.'],
        ['homework',    'домашка',       'домашка',        'I do my homework every evening.'],
        ['classroom',   'класна кімната','классная комната','Our classroom is on the second floor.'],
      ],
      A2: [
        ['university',  'університет',   'университет',    'She studies at the university.'],
        ['subject',     'предмет',       'предмет',        'My favourite subject is biology.'],
        ['grade',       'оцінка',        'оценка',         'I got a top grade.'],
        ['exam',        'іспит',         'экзамен',        'Final exams start in June.'],
        ['library',     'бібліотека',    'библиотека',     'The library is quiet.'],
        ['textbook',    'підручник',     'учебник',        'Open your textbook to page ten.'],
        ['research',    'дослідження',   'исследование',   'I do research on bees.'],
        ['scholarship', 'стипендія',     'стипендия',      'She won a scholarship to Oxford.'],
      ],
      B1: [
        ['curriculum',  'навчальна програма','учебная программа','The new curriculum starts in autumn.'],
        ['assignment',  'завдання',      'задание',        'I finished the assignment early.'],
        ['lecture',     'лекція',        'лекция',         'The lecture lasted two hours.'],
        ['major',       'основна спеціальність','профильная специальность','My major is economics.'],
        ['plagiarism',  'плагіат',       'плагиат',        'Plagiarism is a serious offence.'],
        ['tutor',       'репетитор',     'репетитор',      'I hired a tutor for chemistry.'],
        ['enrol',       'зараховуватися','поступать',      'I enrolled in evening classes.'],
      ],
      B2: [
        ['dissertation','дисертація',    'диссертация',    'My dissertation focuses on AI ethics.'],
        ['curriculum vitae','резюме',    'резюме',         'Attach your curriculum vitae.'],
        ['underachiever','неуспішний учень','неуспевающий ученик','He was labelled an underachiever unfairly.'],
        ['comprehensive','всеосяжний',   'всесторонний',   'We provide comprehensive training.'],
        ['extracurricular','позакласний','внеклассный',    'Extracurricular activities matter.'],
        ['rote learning','зубріння',     'зубрёжка',       'Rote learning rarely sticks.'],
      ],
      C1: [
        ['pedagogy',    'педагогіка',    'педагогика',     'Modern pedagogy values critical thinking.'],
        ['heuristic',   'евристичний',   'эвристический',  'A heuristic approach beats memorisation.'],
        ['valedictorian','найкращий випускник','лучший выпускник','She was valedictorian of her class.'],
        ['cohort',      'когорта',       'когорта',        'The first cohort graduated in 2018.'],
        ['interdisciplinary','міждисциплінарний','междисциплинарный','Interdisciplinary studies are growing.'],
      ],
    },

    // ════════ 7. BODY & HEALTH ════════
    health: {
      name: 'Body & Health',
      icon: '🏥',
      color: '#FFB5AE',
      A1: [
        ['head',        'голова',        'голова',         'My head hurts.'],
        ['hand',        'рука',          'рука',           'Wash your hands.'],
        ['eye',         'око',           'глаз',           'I have blue eyes.'],
        ['leg',         'нога',          'нога',           'My leg is tired.'],
        ['doctor',      'лікар',         'врач',           'Call the doctor.'],
        ['medicine',    'ліки',          'лекарство',      'Take this medicine twice a day.'],
        ['sick',        'хворий',        'больной',        'I feel sick.'],
        ['tooth',       'зуб',           'зуб',            'I broke a tooth.'],
      ],
      A2: [
        ['headache',    'головний біль', 'головная боль',  'I have a terrible headache.'],
        ['cough',       'кашель',        'кашель',         'My cough won’t stop.'],
        ['fever',       'температура',   'температура',    'She has a high fever.'],
        ['injury',      'травма',        'травма',         'A small injury, nothing serious.'],
        ['pharmacy',    'аптека',        'аптека',         'The pharmacy is around the corner.'],
        ['allergy',     'алергія',       'аллергия',       'I have a pollen allergy.'],
        ['exercise',    'тренування',    'тренировка',     'Exercise three times a week.'],
        ['diet',        'дієта',         'диета',          'My doctor put me on a diet.'],
      ],
      B1: [
        ['symptom',     'симптом',       'симптом',        'List your symptoms briefly.'],
        ['prescription','рецепт',        'рецепт',         'I need a prescription refill.'],
        ['diagnosis',   'діагноз',       'диагноз',        'The diagnosis came as a shock.'],
        ['surgery',     'операція',      'операция',       'Surgery is scheduled for Monday.'],
        ['recover',     'одужувати',     'выздоравливать', 'She is recovering well.'],
        ['immunity',    'імунітет',      'иммунитет',      'Sleep boosts immunity.'],
        ['vaccine',     'вакцина',       'вакцина',        'The vaccine works in two weeks.'],
      ],
      B2: [
        ['chronic',     'хронічний',     'хронический',    'He suffers from chronic back pain.'],
        ['nutritionist','дієтолог',      'диетолог',       'A nutritionist redesigned my meals.'],
        ['inflammation','запалення',     'воспаление',     'Reduce inflammation with cold water.'],
        ['hereditary',  'спадковий',     'наследственный', 'The condition is hereditary.'],
        ['therapy',     'терапія',       'терапия',        'Therapy changed my outlook.'],
        ['outbreak',    'спалах хвороби','вспышка болезни','An outbreak closed two schools.'],
      ],
      C1: [
        ['rehabilitation','реабілітація','реабилитация',   'Rehabilitation took six months.'],
        ['contagious',  'заразний',      'заразный',       'The flu is highly contagious.'],
        ['holistic',    'цілісний',      'холистический',  'A holistic approach to wellbeing.'],
        ['placebo',     'плацебо',       'плацебо',        'The placebo effect is real.'],
        ['malignant',   'злоякісний',    'злокачественный','The biopsy ruled out malignant cells.'],
      ],
    },

    // ════════ 8. CLOTHING & FASHION ════════
    clothing: {
      name: 'Clothing & Fashion',
      icon: '👔',
      color: '#D8C5FB',
      A1: [
        ['shirt',       'сорочка',       'рубашка',        'I wear a white shirt to work.'],
        ['shoes',       'взуття',        'обувь',          'I need new shoes.'],
        ['hat',         'капелюх',       'шляпа',          'Wear a hat, it’s sunny.'],
        ['jeans',       'джинси',        'джинсы',         'My jeans are blue.'],
        ['dress',       'сукня',         'платье',         'She has a red dress.'],
        ['coat',        'пальто',        'пальто',         'Take your coat, it’s cold.'],
        ['socks',       'шкарпетки',     'носки',          'Buy black socks.'],
        ['bag',         'сумка',         'сумка',          'My bag is heavy.'],
      ],
      A2: [
        ['outfit',      'наряд',         'наряд',          'Your outfit is perfect.'],
        ['fashion',     'мода',          'мода',           'Fashion changes every season.'],
        ['fit',         'підходити за розміром','подходить по размеру','These trousers don’t fit.'],
        ['size',        'розмір',        'размер',         'What size do you wear?'],
        ['sleeve',      'рукав',         'рукав',          'Roll up your sleeves.'],
        ['pattern',     'візерунок',     'узор',           'I love the floral pattern.'],
        ['brand',       'бренд',         'бренд',          'Which brand is this?'],
        ['scarf',       'шарф',          'шарф',           'A wool scarf for winter.'],
      ],
      B1: [
        ['accessory',   'аксесуар',      'аксессуар',      'A simple accessory completes the look.'],
        ['tailor',      'кравець',       'портной',        'My tailor takes one day.'],
        ['fabric',      'тканина',       'ткань',          'This fabric is breathable.'],
        ['trend',       'тренд',         'тренд',          'Oversized blazers are a trend.'],
        ['vintage',     'вінтаж',        'винтаж',         'I shop vintage on weekends.'],
        ['casual',      'повсякденний',  'повседневный',   'Wear something casual.'],
        ['formal',      'офіційний',     'формальный',     'Formal attire required.'],
      ],
      B2: [
        ['tailored',    'пошитий на замовлення','пошитый на заказ','A tailored jacket fits beautifully.'],
        ['attire',      'вбрання',       'наряд',          'Business attire only.'],
        ['ensemble',    'ансамбль',      'ансамбль',       'Her ensemble was striking.'],
        ['sustainable', 'сталий',        'устойчивый',     'Sustainable fashion is the future.'],
        ['couture',     'кутюр',         'кутюр',          'Couture houses show in Paris.'],
        ['embroidery',  'вишивка',       'вышивка',        'Ukrainian embroidery is famous.'],
      ],
      C1: [
        ['avant-garde', 'авангардний',   'авангардный',    'An avant-garde collection shocked the runway.'],
        ['bespoke',     'індивідуальний','индивидуальный', 'A bespoke suit costs a fortune.'],
        ['minimalist',  'мінімалістичний','минималистичный','Her style is strictly minimalist.'],
        ['monochrome',  'монохромний',   'монохромный',    'I love a monochrome look.'],
        ['repurpose',   'переробляти',   'перепрофилировать','We repurpose old denim into bags.'],
      ],
    },

    // ════════ 9. HOUSE & HOME ════════
    home: {
      name: 'House & Home',
      icon: '🏠',
      color: '#FFC94A',
      A1: [
        ['house',       'дім',           'дом',            'My house is small.'],
        ['kitchen',     'кухня',         'кухня',          'The kitchen is bright.'],
        ['bed',         'ліжко',         'кровать',        'My bed is comfortable.'],
        ['door',        'двері',         'дверь',          'Close the door.'],
        ['window',      'вікно',         'окно',           'Open the window.'],
        ['table',       'стіл',          'стол',           'Put it on the table.'],
        ['chair',       'стілець',       'стул',           'Sit on the chair.'],
        ['lamp',        'лампа',         'лампа',          'Turn on the lamp.'],
      ],
      A2: [
        ['furniture',   'меблі',         'мебель',         'We bought new furniture.'],
        ['neighbour',   'сусід',         'сосед',          'My neighbour is loud.'],
        ['rent',        'оренда',        'аренда',         'Rent is too high.'],
        ['flat',        'квартира',      'квартира',       'I live in a small flat.'],
        ['garden',      'сад',           'сад',            'We have a tiny garden.'],
        ['ceiling',     'стеля',         'потолок',        'The ceiling is high.'],
        ['balcony',     'балкон',        'балкон',         'I drink coffee on the balcony.'],
        ['mortgage',    'іпотека',       'ипотека',        'A mortgage takes thirty years.'],
      ],
      B1: [
        ['appliance',   'побутова техніка','бытовая техника','We need a new appliance for the kitchen.'],
        ['utilities',   'комунальні послуги','коммунальные услуги','Utilities are included in rent.'],
        ['cosy',        'затишний',      'уютный',         'Our living room is cosy in winter.'],
        ['detached',    'окремий',       'отдельный',      'A detached house with a garden.'],
        ['renovate',    'ремонтувати',   'ремонтировать',  'We renovate the bathroom in May.'],
        ['mortgage',    'іпотека',       'ипотека',        'We paid off the mortgage early.'],
        ['landlord',    'орендодавець',  'арендодатель',   'The landlord raised the rent.'],
      ],
      B2: [
        ['en-suite',    'із санвузлом',  'с санузлом',     'The bedroom has an en-suite bathroom.'],
        ['eviction',    'виселення',     'выселение',      'They issued an eviction notice.'],
        ['underfloor heating','тепла підлога','тёплый пол','Underfloor heating is a luxury.'],
        ['airy',        'просторий',     'просторный',     'The flat is airy and bright.'],
        ['feng shui',   'фен-шуй',       'фэн-шуй',        'She designs by feng shui principles.'],
        ['decor',       'декор',         'декор',          'The decor screams the 1980s.'],
      ],
      C1: [
        ['retrofit',    'модернізувати', 'модернизировать','Retrofit insulation cut bills in half.'],
        ['domicile',    'місце проживання','место проживания','Provide your legal domicile.'],
        ['squatter',    'самопоселенець','скваттер',       'Squatters occupied the empty house.'],
        ['gentrification','джентрифікація','джентрификация','Gentrification pushed old residents out.'],
        ['heirloom',    'спадщина',      'фамильная ценность','The clock is a family heirloom.'],
      ],
    },

    // ════════ 10. WEATHER & SEASONS ════════
    weather: {
      name: 'Weather & Seasons',
      icon: '☀️',
      color: '#8FE6E6',
      A1: [
        ['sun',         'сонце',         'солнце',         'The sun is bright.'],
        ['rain',        'дощ',           'дождь',          'Rain is falling.'],
        ['snow',        'сніг',          'снег',           'Snow covers the city.'],
        ['wind',        'вітер',         'ветер',          'A strong wind blows.'],
        ['cold',        'холодний',      'холодный',       'It is cold today.'],
        ['hot',         'спекотний',     'жаркий',         'A hot summer day.'],
        ['cloud',       'хмара',         'облако',         'Look at the clouds.'],
        ['warm',        'теплий',        'тёплый',         'Warm weather is coming.'],
      ],
      A2: [
        ['forecast',    'прогноз',       'прогноз',        'The forecast says rain.'],
        ['humid',       'вологий',       'влажный',        'It’s humid by the sea.'],
        ['storm',       'буря',          'буря',           'A storm is coming.'],
        ['thunder',     'грім',          'гром',           'Thunder woke me up.'],
        ['lightning',   'блискавка',     'молния',         'Lightning struck the tree.'],
        ['freezing',    'крижаний',      'ледяной',        'It’s freezing outside.'],
        ['shower',      'короткий дощ',  'короткий дождь', 'Just a quick shower.'],
        ['breeze',      'легкий вітерець','лёгкий ветерок','A pleasant breeze cooled us.'],
      ],
      B1: [
        ['drizzle',     'мряка',         'морось',         'A light drizzle started.'],
        ['blizzard',    'хуртовина',     'метель',         'A blizzard closed the airport.'],
        ['heatwave',    'спека',         'жара',           'The heatwave lasted ten days.'],
        ['fog',         'туман',         'туман',          'Heavy fog delayed the flights.'],
        ['frost',       'мороз',         'мороз',          'Morning frost killed the basil.'],
        ['mild',        'м’який',        'мягкий',         'A mild autumn so far.'],
        ['gale',        'шквальний вітер','шквалистый ветер','Gales brought down trees.'],
      ],
      B2: [
        ['precipitation','опади',        'осадки',         'Annual precipitation is high.'],
        ['drought',     'посуха',        'засуха',         'A drought is destroying crops.'],
        ['overcast',    'хмарний',       'пасмурный',      'Overcast skies all weekend.'],
        ['scorching',   'пекучий',       'палящий',        'A scorching afternoon by the river.'],
        ['climate',     'клімат',        'климат',         'The climate is changing fast.'],
        ['monsoon',     'мусон',         'муссон',         'Monsoon rains flood the streets.'],
      ],
      C1: [
        ['inclement',   'непогожий',     'ненастный',      'Inclement weather cancelled the match.'],
        ['torrential',  'зливовий',      'проливной',      'Torrential rain caused mudslides.'],
        ['arid',        'посушливий',    'засушливый',     'Arid regions struggle with water.'],
        ['balmy',       'м’який і теплий','тёплый и приятный','A balmy evening on the terrace.'],
        ['microclimate','мікроклімат',   'микроклимат',    'The valley has its own microclimate.'],
      ],
    },

    // ════════ 11. ANIMALS ════════
    animals: {
      name: 'Animals',
      icon: '🐾',
      color: '#CDF24F',
      A1: [
        ['dog',         'пес',           'собака',         'My dog is friendly.'],
        ['cat',         'кіт',           'кот',            'The cat is on the chair.'],
        ['bird',        'птах',          'птица',          'A bird is singing.'],
        ['fish',        'риба',          'рыба',           'Fish live in water.'],
        ['horse',       'кінь',          'лошадь',         'I ride a horse.'],
        ['cow',         'корова',        'корова',         'Cows give milk.'],
        ['rabbit',      'кролик',        'кролик',         'A small white rabbit.'],
        ['mouse',       'миша',          'мышь',           'A mouse ran across the floor.'],
      ],
      A2: [
        ['pet',         'улюбленець',    'питомец',        'I have two pets at home.'],
        ['wild',        'дикий',         'дикий',          'Wild animals avoid people.'],
        ['zoo',         'зоопарк',       'зоопарк',        'Our local zoo is big.'],
        ['cage',        'клітка',        'клетка',         'The bird left the cage.'],
        ['farm',        'ферма',         'ферма',          'A farm with cows and sheep.'],
        ['feathers',    'пір’я',         'перья',          'Soft white feathers.'],
        ['paw',         'лапа',          'лапа',           'The dog hurt its paw.'],
        ['tail',        'хвіст',         'хвост',          'The cat wagged its tail.'],
      ],
      B1: [
        ['species',     'вид',           'вид',            'A new species was discovered.'],
        ['mammal',      'ссавець',       'млекопитающее',  'Whales are mammals.'],
        ['predator',    'хижак',         'хищник',         'The lion is an apex predator.'],
        ['prey',        'здобич',        'добыча',         'Owls hunt their prey at night.'],
        ['herd',        'стадо',         'стадо',          'A herd of elephants crossed the road.'],
        ['extinct',     'вимерлий',      'вымерший',       'The mammoth is extinct.'],
        ['migrate',     'мігрувати',     'мигрировать',    'Birds migrate every autumn.'],
      ],
      B2: [
        ['nocturnal',   'нічний',        'ночной',         'Owls are nocturnal birds.'],
        ['camouflage',  'маскування',    'маскировка',     'The chameleon uses camouflage.'],
        ['herbivore',   'травоїдний',    'травоядное',     'A herbivore eats only plants.'],
        ['endangered',  'під загрозою',  'на грани вымирания','Pandas are endangered.'],
        ['domestication','одомашнення',  'одомашнивание',  'Dog domestication began long ago.'],
        ['poacher',     'браконьєр',     'браконьер',      'Poachers threaten rhinos.'],
      ],
      C1: [
        ['feral',       'здичавілий',    'одичавший',      'Feral cats roam the alleys.'],
        ['biodiversity','біорізноманіття','биоразнообразие','Biodiversity is collapsing.'],
        ['ecosystem',   'екосистема',    'экосистема',     'Each ecosystem is fragile.'],
        ['evolution',   'еволюція',      'эволюция',       'Evolution shapes every species.'],
        ['symbiosis',   'симбіоз',       'симбиоз',        'Bees and flowers share a symbiosis.'],
      ],
    },

    // ════════ 12. NATURE & ENVIRONMENT ════════
    nature: {
      name: 'Nature & Environment',
      icon: '🌳',
      color: '#CDF24F',
      A1: [
        ['tree',        'дерево',        'дерево',         'A tall tree near the lake.'],
        ['flower',      'квітка',        'цветок',         'I picked a yellow flower.'],
        ['river',       'річка',         'река',           'The river is wide.'],
        ['mountain',    'гора',          'гора',           'I love mountains.'],
        ['sea',         'море',          'море',           'The sea is calm today.'],
        ['forest',      'ліс',           'лес',            'We walked in the forest.'],
        ['grass',       'трава',         'трава',          'The grass is green.'],
        ['lake',        'озеро',         'озеро',          'A small lake nearby.'],
      ],
      A2: [
        ['landscape',   'ландшафт',      'ландшафт',       'A breathtaking landscape.'],
        ['valley',      'долина',        'долина',         'The valley is full of vineyards.'],
        ['waterfall',   'водоспад',      'водопад',        'A loud waterfall in the canyon.'],
        ['desert',      'пустеля',       'пустыня',        'The desert at night is cold.'],
        ['island',      'острів',        'остров',         'A tiny island in the bay.'],
        ['shore',       'берег',         'берег',          'I walked along the shore.'],
        ['stream',      'струмок',       'ручей',          'A clear stream runs nearby.'],
        ['meadow',      'лука',          'луг',            'A meadow full of daisies.'],
      ],
      B1: [
        ['pollution',   'забруднення',   'загрязнение',    'Pollution is a global issue.'],
        ['recycle',     'переробляти',   'перерабатывать', 'We recycle every week.'],
        ['renewable',   'відновлюваний', 'возобновляемый', 'Renewable energy is growing.'],
        ['habitat',     'середовище проживання','среда обитания','Forests are a key habitat.'],
        ['glacier',     'льодовик',      'ледник',         'Glaciers are melting fast.'],
        ['canyon',      'каньйон',       'каньон',         'The Grand Canyon is huge.'],
        ['peninsula',   'півострів',     'полуостров',     'A narrow peninsula juts into the sea.'],
      ],
      B2: [
        ['sustainable', 'сталий',        'устойчивый',     'Sustainable farming matters.'],
        ['conservation','охорона природи','охрана природы','Conservation needs funding.'],
        ['ecosystem',   'екосистема',    'экосистема',     'A fragile ecosystem.'],
        ['deforestation','знеліснення',  'обезлесение',    'Deforestation accelerates.'],
        ['biodiversity','біорізноманіття','биоразнообразие','Biodiversity loss is rapid.'],
        ['organic',     'органічний',    'органический',   'I buy organic vegetables.'],
      ],
      C1: [
        ['fauna',       'фауна',         'фауна',          'The fauna of the wetlands amazes.'],
        ['terrain',     'місцевість',    'местность',      'The terrain is treacherous.'],
        ['precipice',   'прірва',        'обрыв',          'A sheer precipice lay ahead.'],
        ['undulating',  'хвилястий',     'волнистый',      'Undulating hills stretch for miles.'],
        ['pristine',    'незайманий',    'нетронутый',     'A pristine alpine lake.'],
      ],
    },

    // ════════ 13. SPORTS & FITNESS ════════
    sports: {
      name: 'Sports & Fitness',
      icon: '⚽',
      color: '#FFC94A',
      A1: [
        ['football',    'футбол',        'футбол',         'I play football on Sundays.'],
        ['ball',        'м’яч',          'мяч',            'Pass me the ball.'],
        ['run',         'бігати',        'бегать',         'I run in the morning.'],
        ['swim',        'плавати',       'плавать',        'I swim in summer.'],
        ['team',        'команда',       'команда',        'Our team won.'],
        ['win',         'перемога',      'победа',         'A big win for us.'],
        ['gym',         'спортзал',      'спортзал',       'I go to the gym.'],
        ['bike',        'велосипед',     'велосипед',      'A red bike for my son.'],
      ],
      A2: [
        ['coach',       'тренер',        'тренер',         'Our coach is strict.'],
        ['match',       'матч',          'матч',           'The match was exciting.'],
        ['score',       'рахунок',       'счёт',           'The score is two to one.'],
        ['referee',     'суддя',         'судья',          'The referee made a fair call.'],
        ['stadium',     'стадіон',       'стадион',        'The stadium was packed.'],
        ['training',    'тренування',    'тренировка',     'Training starts at six.'],
        ['marathon',    'марафон',       'марафон',        'I ran my first marathon.'],
        ['injury',      'травма',        'травма',         'A small injury kept him out.'],
      ],
      B1: [
        ['championship','чемпіонат',     'чемпионат',      'The championship is in May.'],
        ['fitness',     'фітнес',        'фитнес',         'My fitness improved fast.'],
        ['endurance',   'витривалість',  'выносливость',   'Endurance comes with time.'],
        ['warm-up',     'розминка',      'разминка',       'Never skip the warm-up.'],
        ['stretching',  'розтяжка',      'растяжка',       'Stretching prevents injuries.'],
        ['tournament',  'турнір',        'турнир',         'The tournament starts on Friday.'],
        ['amateur',     'аматорський',   'любительский',   'I play amateur tennis.'],
      ],
      B2: [
        ['stamina',     'витривалість',  'выносливость',   'Climbers need huge stamina.'],
        ['agility',     'спритність',    'ловкость',       'Agility is a fencer’s asset.'],
        ['rivalry',     'суперництво',   'соперничество',  'A historic rivalry resumes tonight.'],
        ['underdog',    'аутсайдер',     'аутсайдер',      'Everyone loves an underdog.'],
        ['drills',      'вправи',        'упражнения',     'Repetitive drills build muscle memory.'],
        ['benchmark',   'еталон',        'эталон',         'He set a new benchmark.'],
      ],
      C1: [
        ['doping',      'допінг',        'допинг',         'Doping tests are stricter than ever.'],
        ['plateau',     'застій',        'плато',          'I hit a fitness plateau in May.'],
        ['acumen',      'кмітливість',   'смекалка',       'Tactical acumen wins championships.'],
        ['gruelling',   'виснажливий',   'изнурительный',  'A gruelling six-hour stage.'],
        ['hone',        'удосконалювати','оттачивать',     'She hones her technique daily.'],
      ],
    },

    // ════════ 14. HOBBIES & LEISURE ════════
    hobbies: {
      name: 'Hobbies & Leisure',
      icon: '🎨',
      color: '#D8C5FB',
      A1: [
        ['read',        'читати',        'читать',         'I read every evening.'],
        ['draw',        'малювати',      'рисовать',       'My son loves to draw.'],
        ['sing',        'співати',       'петь',           'I sing in the shower.'],
        ['dance',       'танцювати',     'танцевать',      'We dance every Friday.'],
        ['game',        'гра',           'игра',           'Let’s play a game.'],
        ['walk',        'прогулянка',    'прогулка',       'A walk before dinner.'],
        ['photo',       'фото',          'фото',           'Take a photo of us.'],
        ['cook',        'готувати',      'готовить',       'I cook on weekends.'],
      ],
      A2: [
        ['knitting',    'в’язання',      'вязание',        'Knitting calms me down.'],
        ['gardening',   'садівництво',   'садоводство',    'Gardening is my therapy.'],
        ['painting',    'живопис',       'живопись',       'I took up painting last year.'],
        ['hiking',      'піший туризм',  'пеший туризм',   'Hiking is great exercise.'],
        ['camping',     'кемпінг',       'кемпинг',        'A camping trip in July.'],
        ['fishing',     'риболовля',     'рыбалка',        'Fishing requires patience.'],
        ['baking',      'випікання',     'выпекание',      'Baking bread on Sundays.'],
        ['cycling',     'велосипедний спорт','велоспорт',  'Cycling along the river.'],
      ],
      B1: [
        ['craft',       'ремесло',       'ремесло',        'Pottery is an ancient craft.'],
        ['collect',     'колекціонувати','коллекционировать','I collect old postcards.'],
        ['leisure',     'дозвілля',      'досуг',          'I rarely have leisure time.'],
        ['enthusiast',  'ентузіаст',     'энтузиаст',      'A board game enthusiast.'],
        ['workshop',    'майстерня',     'мастерская',     'I joined a pottery workshop.'],
        ['exhibition',  'виставка',      'выставка',       'The exhibition runs till Sunday.'],
        ['journal',     'щоденник',      'дневник',        'I keep a daily journal.'],
      ],
      B2: [
        ['knack',       'хист',          'сноровка',       'She has a knack for languages.'],
        ['immerse',     'занурюватися',  'погружаться',    'I immerse myself in pottery.'],
        ['amateurish',  'аматорський',   'дилетантский',   'My sketches look amateurish.'],
        ['pastime',     'захоплення',    'хобби',          'Chess is a quiet pastime.'],
        ['unwind',      'розслаблятися', 'расслабляться',  'I unwind by playing piano.'],
        ['enrich',      'збагачувати',   'обогащать',      'Hobbies enrich your life.'],
      ],
      C1: [
        ['aficionado',  'затятий шанувальник','страстный любитель','An opera aficionado for years.'],
        ['dabble',      'бавитися',      'баловаться',     'I dabble in watercolour.'],
        ['fervour',     'запал',         'пыл',            'She paints with fervour.'],
        ['idiosyncrasy','дивацтво',      'причуда',        'Birdwatching is a charming idiosyncrasy.'],
        ['virtuoso',    'віртуоз',       'виртуоз',        'A guitar virtuoso headlined the festival.'],
      ],
    },

    // ════════ 15. TECHNOLOGY & INTERNET ════════
    tech: {
      name: 'Technology & Internet',
      icon: '💻',
      color: '#8FE6E6',
      A1: [
        ['phone',       'телефон',       'телефон',        'I lost my phone.'],
        ['computer',    'комп’ютер',     'компьютер',      'This computer is fast.'],
        ['internet',    'інтернет',      'интернет',       'The internet is down.'],
        ['email',       'імейл',         'имейл',          'Send me an email.'],
        ['app',         'застосунок',    'приложение',     'Download the app.'],
        ['screen',      'екран',         'экран',          'The screen is broken.'],
        ['mouse',       'миша',          'мышь',           'A wireless mouse.'],
        ['game',        'гра',           'игра',           'Let’s play a game.'],
      ],
      A2: [
        ['download',    'завантажувати', 'скачивать',      'Download the new version.'],
        ['password',    'пароль',        'пароль',         'Change your password.'],
        ['website',     'вебсайт',       'веб-сайт',       'Check out our website.'],
        ['software',    'програмне забезпечення','программное обеспечение','We need new software.'],
        ['device',      'пристрій',      'устройство',     'A small wearable device.'],
        ['battery',     'батарея',       'батарея',        'My battery is low.'],
        ['cloud',       'хмара',         'облако',         'Files are in the cloud.'],
        ['wireless',    'безпровідний',  'беспроводной',   'A wireless keyboard.'],
      ],
      B1: [
        ['firewall',    'брандмауер',    'файрвол',        'The firewall blocks intruders.'],
        ['encryption',  'шифрування',    'шифрование',     'End-to-end encryption is standard.'],
        ['hacker',      'хакер',         'хакер',          'A hacker stole the data.'],
        ['backup',      'резервна копія','резервная копия','Always make a backup.'],
        ['streaming',   'стрімінг',      'стриминг',       'Streaming sites dominate TV.'],
        ['interface',   'інтерфейс',     'интерфейс',      'The interface is intuitive.'],
        ['gadget',      'ґаджет',        'гаджет',         'A useful kitchen gadget.'],
      ],
      B2: [
        ['algorithm',   'алгоритм',      'алгоритм',       'The algorithm ranks results.'],
        ['cybersecurity','кібербезпека', 'кибербезопасность','Cybersecurity matters daily.'],
        ['bandwidth',   'пропускна здатність','пропускная способность','Limited bandwidth slowed us down.'],
        ['debugging',   'налагодження',  'отладка',        'Debugging took all night.'],
        ['scalable',    'масштабований', 'масштабируемый', 'A scalable architecture.'],
        ['phishing',    'фішинг',        'фишинг',         'Phishing emails got smarter.'],
      ],
      C1: [
        ['proprietary', 'власницький',   'проприетарный',  'Proprietary software locks customers in.'],
        ['decentralised','децентралізований','децентрализованный','A decentralised network resists censorship.'],
        ['agnostic',    'агностичний',   'агностический',  'Our tool is platform-agnostic.'],
        ['paradigm',    'парадигма',     'парадигма',      'A new computing paradigm.'],
        ['latency',     'затримка',      'задержка',       'Latency below 30 ms feels instant.'],
      ],
    },

    // ════════ 16. MONEY & SHOPPING ════════
    money: {
      name: 'Money & Shopping',
      icon: '💰',
      color: '#CDF24F',
      A1: [
        ['money',       'гроші',         'деньги',         'I have no money.'],
        ['shop',        'магазин',       'магазин',        'A new shop opened.'],
        ['price',       'ціна',          'цена',           'The price is fair.'],
        ['buy',         'купувати',      'покупать',       'I want to buy milk.'],
        ['sell',        'продавати',     'продавать',      'They sell flowers.'],
        ['pay',         'платити',       'платить',        'I’ll pay in cash.'],
        ['card',        'картка',        'карта',          'I pay by card.'],
        ['receipt',     'чек',           'чек',            'Save the receipt.'],
      ],
      A2: [
        ['expensive',   'дорогий',       'дорогой',        'Too expensive for me.'],
        ['cheap',       'дешевий',       'дешёвый',        'A cheap flight to Rome.'],
        ['discount',    'знижка',        'скидка',         'A 20 percent discount.'],
        ['budget',      'бюджет',        'бюджет',         'My monthly budget is tight.'],
        ['cash',        'готівка',       'наличные',       'Pay cash, please.'],
        ['change',      'решта',         'сдача',          'Keep the change.'],
        ['bill',        'рахунок',       'счёт',           'The bill, please.'],
        ['savings',     'заощадження',   'сбережения',     'My savings ran out.'],
      ],
      B1: [
        ['afford',      'дозволити собі','позволить себе', 'I can’t afford a new car.'],
        ['debt',        'борг',          'долг',           'I’m paying off student debt.'],
        ['loan',        'кредит',        'кредит',         'A small loan for the renovation.'],
        ['refund',      'повернення коштів','возврат денег','Request a refund within 30 days.'],
        ['exchange rate','обмінний курс','обменный курс',  'The exchange rate hit a new low.'],
        ['invest',      'інвестувати',   'инвестировать',  'I invest in index funds.'],
        ['receipt',     'квитанція',     'квитанция',      'Keep the receipt for warranty.'],
      ],
      B2: [
        ['frugal',      'ощадливий',     'бережливый',     'My grandfather was famously frugal.'],
        ['splurge',     'розщедритися',  'раскошелиться',  'I splurged on a watch last week.'],
        ['lavish',      'розкішний',     'роскошный',      'A lavish wedding by the lake.'],
        ['inflation',   'інфляція',      'инфляция',       'Inflation eats your savings.'],
        ['mortgage',    'іпотека',       'ипотека',        'Mortgage rates climbed again.'],
        ['stipend',     'стипендія',     'стипендия',      'A modest monthly stipend.'],
      ],
      C1: [
        ['solvent',     'платоспроможний','платёжеспособный','The firm is barely solvent.'],
        ['extravagance','марнотратство', 'расточительность','A daily taxi is sheer extravagance.'],
        ['penny-pinching','скнара',     'жадюга',         'Penny-pinching turned them miserable.'],
        ['speculate',   'спекулювати',   'спекулировать',  'Traders speculate on volatility.'],
        ['recession',   'рецесія',       'рецессия',       'A mild recession is forecast.'],
      ],
    },

    // ════════ 17. TRANSPORT ════════
    transport: {
      name: 'Transport',
      icon: '🚌',
      color: '#FFB5AE',
      A1: [
        ['car',         'автомобіль',    'автомобиль',     'My car is old.'],
        ['bus',         'автобус',       'автобус',        'Take bus number 12.'],
        ['train',       'потяг',         'поезд',          'The train is fast.'],
        ['plane',       'літак',         'самолёт',        'I love planes.'],
        ['bike',        'велосипед',     'велосипед',      'A red bike for kids.'],
        ['walk',        'іти пішки',     'идти пешком',    'I walk to school.'],
        ['ride',        'їхати',         'ехать',          'I ride to work daily.'],
        ['ticket',      'квиток',        'билет',          'Buy a one-way ticket.'],
      ],
      A2: [
        ['traffic',     'рух/затори',    'движение/пробки','Traffic is awful today.'],
        ['petrol',      'бензин',        'бензин',         'Petrol prices rose again.'],
        ['driver',      'водій',         'водитель',       'A polite taxi driver.'],
        ['highway',     'шосе',          'шоссе',          'A long highway through the desert.'],
        ['parking',     'парковка',      'парковка',       'Parking is hard downtown.'],
        ['station',     'станція',       'станция',        'The station is crowded.'],
        ['platform',    'платформа',     'платформа',      'Wait on platform 3.'],
        ['cycle',       'їздити на велосипеді','ездить на велосипеде','I cycle every weekend.'],
      ],
      B1: [
        ['commute',     'добиратися',    'добираться',     'My commute takes an hour.'],
        ['public transport','громадський транспорт','общественный транспорт','Public transport runs late.'],
        ['carpool',     'спільні поїздки','совместные поездки','We carpool to save fuel.'],
        ['rush hour',   'година пік',    'час пик',        'Avoid rush hour if you can.'],
        ['detour',      'об’їзд',        'объезд',         'A detour added 30 minutes.'],
        ['fare',        'плата за проїзд','плата за проезд','Fares went up by 10%.'],
        ['route',       'маршрут',       'маршрут',        'The shortest route to the airport.'],
      ],
      B2: [
        ['congestion',  'затори',        'пробки',         'Congestion charges deter drivers.'],
        ['emission',    'викид',         'выброс',         'Lower emissions, please.'],
        ['gridlock',    'повний затор', 'полный затор',   'A gridlock paralysed the city.'],
        ['ridesharing', 'кар-шерінг',    'каршеринг',      'Ridesharing is on the rise.'],
        ['toll',        'плата за проїзд','платная дорога','A toll road cuts the trip short.'],
        ['shuttle',     'трансфер',      'трансфер',       'A free shuttle to the airport.'],
      ],
      C1: [
        ['expedite',    'пришвидшувати', 'ускорять',       'A new tunnel will expedite freight.'],
        ['logistics',   'логістика',     'логистика',      'Logistics is everything in retail.'],
        ['infrastructure','інфраструктура','инфраструктура','Failing infrastructure needs funds.'],
        ['fuselage',    'фюзеляж',       'фюзеляж',        'The fuselage is made of composites.'],
        ['mass transit','масовий транспорт','общественный транспорт','Mass transit reduces emissions.'],
      ],
    },

    // ════════ 18. CITY & PLACES ════════
    city: {
      name: 'City & Places',
      icon: '🏙️',
      color: '#8FE6E6',
      A1: [
        ['street',      'вулиця',        'улица',          'A long, quiet street.'],
        ['park',        'парк',          'парк',           'I run in the park.'],
        ['hospital',    'лікарня',       'больница',       'The hospital is close.'],
        ['bank',        'банк',          'банк',           'The bank closes at 5.'],
        ['museum',      'музей',         'музей',          'The museum is free today.'],
        ['cinema',      'кінотеатр',     'кинотеатр',      'The new cinema is huge.'],
        ['cafe',        'кав’ярня',      'кафе',           'A small cafe on the corner.'],
        ['library',     'бібліотека',    'библиотека',     'The library is silent.'],
      ],
      A2: [
        ['neighbourhood','район',        'район',          'A quiet neighbourhood.'],
        ['skyscraper',  'хмарочос',      'небоскрёб',      'A glass skyscraper downtown.'],
        ['fountain',    'фонтан',        'фонтан',         'The fountain is dry in summer.'],
        ['bridge',      'міст',          'мост',           'Cross the bridge and turn left.'],
        ['avenue',      'проспект',      'проспект',       'Fifth Avenue is famous.'],
        ['suburb',      'передмістя',    'пригород',       'They moved to a quiet suburb.'],
        ['square',      'площа',         'площадь',        'The main square is huge.'],
        ['monument',    'пам’ятник',     'памятник',       'A monument honouring poets.'],
      ],
      B1: [
        ['pedestrian',  'пішохід',       'пешеход',        'A pedestrian crossing here, please.'],
        ['boulevard',   'бульвар',       'бульвар',        'A tree-lined boulevard.'],
        ['outskirts',   'околиці',       'окраины',        'We live on the outskirts.'],
        ['urban',       'міський',       'городской',      'Urban life never stops.'],
        ['rural',       'сільський',     'сельский',       'Rural Ukraine is beautiful.'],
        ['cobblestone', 'бруківка',      'мостовая',       'A cobblestone alley in the old town.'],
        ['district',    'район',         'район',          'The financial district hums by day.'],
      ],
      B2: [
        ['gentrified',  'джентрифікований','джентрифицированный','The gentrified quarter feels sterile.'],
        ['bustling',    'жвавий',        'оживлённый',     'A bustling market every Saturday.'],
        ['quaint',      'мальовничий',   'причудливый',    'A quaint village by the river.'],
        ['affluent',    'заможний',      'зажиточный',     'An affluent neighbourhood.'],
        ['derelict',    'занедбаний',    'заброшенный',    'A derelict warehouse turned gallery.'],
        ['landmark',    'визначна пам’ятка','достопримечательность','The cathedral is a landmark.'],
      ],
      C1: [
        ['metropolis',  'мегаполіс',     'мегаполис',      'A teeming metropolis.'],
        ['enclave',     'анклав',        'анклав',         'A small expat enclave.'],
        ['conurbation', 'агломерація',   'агломерация',    'The conurbation covers four counties.'],
        ['promenade',   'набережна',     'набережная',     'An evening promenade by the sea.'],
        ['edifice',     'будівля',       'здание',         'An imposing edifice from the 1920s.'],
      ],
    },

    // ════════ 19. EMOTIONS & FEELINGS ════════
    emotions: {
      name: 'Emotions & Feelings',
      icon: '😊',
      color: '#FFB5AE',
      A1: [
        ['happy',       'щасливий',      'счастливый',     'I am happy today.'],
        ['sad',         'сумний',        'грустный',       'He looks sad.'],
        ['angry',       'сердитий',      'сердитый',       'Don’t be angry.'],
        ['tired',       'втомлений',     'уставший',       'I am tired.'],
        ['scared',      'наляканий',     'испуганный',     'The cat is scared.'],
        ['hungry',      'голодний',      'голодный',       'I am hungry.'],
        ['glad',        'радий',         'рад',            'Glad to meet you.'],
        ['nice',        'приємний',      'приятный',       'A nice surprise.'],
      ],
      A2: [
        ['bored',       'нудний',        'скучающий',      'I am bored at home.'],
        ['excited',     'збуджений',     'возбуждённый',   'She’s excited for the trip.'],
        ['proud',       'гордий',        'гордый',         'I’m proud of my team.'],
        ['nervous',     'нервовий',      'нервный',        'Don’t be nervous before exams.'],
        ['relaxed',     'розслаблений', 'расслабленный',  'I feel relaxed after a walk.'],
        ['confused',    'спантеличений','растерянный',    'I’m confused by your message.'],
        ['surprised',   'здивований',    'удивлённый',     'I was pleasantly surprised.'],
        ['lonely',      'самотній',      'одинокий',       'I felt lonely in the new city.'],
      ],
      B1: [
        ['anxious',     'тривожний',     'тревожный',      'I get anxious in crowds.'],
        ['grateful',    'вдячний',       'благодарный',    'I’m grateful for your help.'],
        ['frustrated',  'роздратований', 'раздражённый',   'Slow internet makes me frustrated.'],
        ['overwhelmed', 'перевантажений','подавленный',    'I feel overwhelmed by tasks.'],
        ['content',     'задоволений',   'довольный',      'A simple, content life.'],
        ['homesick',    'тужливий',      'тоскующий',      'I’m homesick after one month.'],
        ['hopeful',     'сповнений надії','полный надежды','Doctors are hopeful.'],
      ],
      B2: [
        ['apprehensive','стурбований',   'обеспокоенный',  'I’m apprehensive about the trip.'],
        ['indifferent', 'байдужий',      'равнодушный',    'He stayed indifferent to praise.'],
        ['resentful',   'обурений',      'обиженный',      'I’m resentful of the criticism.'],
        ['elated',      'у захваті',     'воодушевлённый', 'She was elated after winning.'],
        ['composed',    'спокійний',     'собранный',      'He stayed composed under pressure.'],
        ['melancholy',  'меланхолія',    'меланхолия',     'A wave of melancholy hit me.'],
      ],
      C1: [
        ['ambivalent',  'двозначний',    'двойственный',   'I’m ambivalent about the offer.'],
        ['exuberant',   'життєрадісний', 'жизнерадостный', 'An exuberant welcome.'],
        ['disconsolate','невтішний',     'безутешный',     'She was disconsolate for weeks.'],
        ['stoic',       'стоїчний',      'стоический',     'A stoic acceptance of fate.'],
        ['euphoric',    'ейфоричний',    'эйфорический',   'Fans were euphoric after the goal.'],
      ],
    },

    // ════════ 20. PHRASAL VERBS (common) ════════
    phrasal: {
      name: 'Phrasal Verbs',
      icon: '🔤',
      color: '#D8C5FB',
      A1: [
        ['get up',      'вставати',      'вставать',       'I get up at seven.'],
        ['sit down',    'сідати',        'садиться',       'Please sit down.'],
        ['stand up',    'вставати',      'вставать',       'Stand up, the bell rang.'],
        ['turn on',     'вмикати',       'включать',       'Turn on the light.'],
        ['turn off',    'вимикати',      'выключать',      'Turn off the TV, please.'],
        ['put on',      'одягати',       'надевать',       'Put on your jacket.'],
        ['take off',    'знімати',       'снимать',        'Take off your shoes.'],
        ['look at',     'дивитися на',   'смотреть на',    'Look at this picture.'],
      ],
      A2: [
        ['give up',     'здаватися',     'сдаваться',      'Don’t give up so easily.'],
        ['find out',    'дізнаватися',   'узнавать',       'I’ll find out tomorrow.'],
        ['look after',  'доглядати',     'присматривать',  'I look after my niece on Fridays.'],
        ['pick up',     'забирати',      'забирать',       'I pick up the kids at 3.'],
        ['set up',      'налаштовувати', 'настраивать',    'Set up your phone first.'],
        ['run out',     'закінчуватися', 'заканчиваться',  'We ran out of milk.'],
        ['get along',   'ладнати',       'ладить',         'I get along with my boss.'],
        ['turn down',   'відхиляти',     'отказывать',     'They turned down my offer.'],
      ],
      B1: [
        ['put off',     'відкладати',    'откладывать',    'Don’t put off the test prep.'],
        ['bring up',    'виховувати',    'воспитывать',    'My grandmother brought me up.'],
        ['come up with','придумувати',   'придумывать',    'I came up with a wild idea.'],
        ['look forward to','чекати з нетерпінням','с нетерпением ждать','I look forward to seeing you.'],
        ['carry out',   'виконувати',    'выполнять',      'We carried out the experiment.'],
        ['take over',   'перебирати',    'забирать',       'A new manager will take over.'],
        ['put up with', 'миритися',      'мириться',       'I won’t put up with rudeness.'],
      ],
      B2: [
        ['call off',    'скасовувати',   'отменять',       'They called off the wedding.'],
        ['account for', 'пояснювати',    'объяснять',      'How do you account for the loss?'],
        ['dwell on',    'зациклюватися', 'зацикливаться',  'Don’t dwell on past mistakes.'],
        ['back up',     'підтримувати',  'подтверждать',   'I’ll back up your story.'],
        ['fall through','зриватися',     'срываться',      'The deal fell through last week.'],
        ['stick to',    'дотримуватися', 'придерживаться', 'Stick to the plan.'],
      ],
      C1: [
        ['shy away from','уникати',      'избегать',       'Politicians shy away from straight answers.'],
        ['mull over',   'обмірковувати', 'обдумывать',     'I’ll mull over your offer.'],
        ['gloss over',  'обходити стороною','обходить стороной','You glossed over the main issue.'],
        ['live up to',  'відповідати очікуванням','соответствовать ожиданиям','The sequel didn’t live up to the original.'],
        ['weigh in on', 'висловлюватися про','высказываться о','Experts weighed in on the policy.'],
      ],
    },
  };

  // Helpers ───────────────────────────────────────────────────────────────

  function ids() { return Object.keys(TOPICS); }
  function listTopics() {
    return ids().map(id => ({
      id,
      name: TOPICS[id].name,
      icon: TOPICS[id].icon,
      color: TOPICS[id].color,
      counts: ['A1','A2','B1','B2','C1'].reduce((a, l) => (a[l] = TOPICS[id][l]?.length || 0, a), {}),
    }));
  }
  function getTopic(id) { return TOPICS[id] || null; }
  function getWords(id, level) {
    const t = TOPICS[id]; if (!t) return [];
    if (level && level !== 'mix') return (t[level] || []).map(toObj);
    const all = [];
    ['A1','A2','B1','B2','C1'].forEach(L => (t[L] || []).forEach(w => all.push(toObj(w, L))));
    return all;
  }
  function toObj(t, level) {
    return { en: t[0], uk: t[1], ru: t[2], ex: t[3], level };
  }
  function pick(id, level, n) {
    const arr = getWords(id, level);
    const shuffled = arr.slice().sort(() => Math.random() - 0.5);
    return n ? shuffled.slice(0, n) : shuffled;
  }

  window.TEACHEDOS_VOCAB = {
    version: 1,
    topics: TOPICS,
    ids,
    listTopics,
    getTopic,
    getWords,
    pick,
  };
})();
